include $(DOCBOOK_SVN)/buildtools/Makefile.incl

PARAMBASE=param
XSLFILES=param.xsl profile-docbook.xsl
ALLTARGETS=$(XSLFILES) titlepage.templates.xsl
PROFILECONDITION=fo
TARGETNS=http://www.w3.org/1999/XSL/Format

include ../Makefile.incl
