#!/bin/bash

# This shell script will definitely need to be hacked to run on your system!
# This script is usually called by the xslt script.
#
# Usage: saxon [shellopts] src.xml style.xsl output.{xml|html} [styleopts]
#

DONE=0
VERSION=651
DEBUG=0
JAR=0
#XARG=""
#YARG=""
#RARG=""
XARG="-x com.sun.resolver.tools.ResolvingXMLReader"
YARG="-y com.sun.resolver.tools.ResolvingXMLReader"
RARG="-r com.sun.resolver.tools.CatalogResolver"
MEMORY=""
QUIET=0

while [ "$DONE" = "0" ]; do
    case $1 in
	-d)	DEBUG=1;
		shift;
		;;
	-j)	JAR=1;
	        echo "Using jar file for extension classes"
		shift;
		;;
	-651)	VERSION=651;
		shift;
		;;
	-65)	VERSION=65;
		shift;
		;;
	-644)	VERSION=644;
		shift;
		;;
	-643)	VERSION=643;
		shift;
		;;
	-642)	VERSION=642;
		shift;
		;;
	-64)	VERSION=64;
		shift;
		;;
	-63)	VERSION=63;
		shift;
		;;
	-622)	VERSION=622;
		shift;
		;;
	-621)	VERSION=621;
		shift;
		;;
	-62)	VERSION=62;
		shift;
		;;
	-61)	VERSION=61;
		shift;
		;;
	-6)	VERSION=6;
		RARG=""
		shift;
		;;
	-5)	VERSION=5;
		RARG=""
		shift;
		;;
	-x)     shift;
		XARG="-x $1";
		shift;
		;;
	-y)     shift;
		YARG="-y $1";
		shift;
		;;
	-r)     shift;
		RARG="-r $1";
		shift;
		;;
        -m)     shift
		MEMORY="-Xmx$1";
		shift;
		;;
        -q)     shift
		QUIET=1
		;;
	-*)	DONE=1;
		echo "Unexpected arguments!";
		echo "  $*"
		exit;
		;;
	*)	DONE=1
    esac
done

XMLSRC=$1; shift
XMLSTY=$1; shift
OUTPUT=$1; shift

if [ "$OUTPUT" = "-" ]; then
    OUTPUT="";
fi

if [ "$OUTPUT" != "" ]; then
  OUTPUT="-o $OUTPUT"
fi

case $VERSION in
   651)	SAXON="/usr/local/java/saxon-6.5.1/saxon.jar"
	SAXON_DEBUG="/usr/local/java/saxon-6.5.1/.classes"
	NDWEXT="/sourceforge/docbook/xsl/extensions/saxon643/.classes";
	if [ "$JAR" = "1" ]; then
	    NDWEXT="/sourceforge/docbook/xsl/extensions/saxon643.jar"
	fi
	;;
   65)	SAXON="/usr/local/java/saxon-6.5/saxon.jar"
	SAXON_DEBUG="/usr/local/java/saxon-6.4.3/.classes"
	NDWEXT="/sourceforge/docbook/xsl/extensions/saxon643/.classes";
	if [ "$JAR" = "1" ]; then
	    NDWEXT="/sourceforge/docbook/xsl/extensions/saxon65.jar"
	fi
	;;
   644)	SAXON="/usr/local/java/saxon-6.4.4/saxon.jar"
	SAXON_DEBUG="/usr/local/java/saxon-6.4.3/.classes"
	NDWEXT="/sourceforge/docbook/xsl/extensions/saxon643/.classes";
	if [ "$JAR" = "1" ]; then
	    NDWEXT="/sourceforge/docbook/xsl/extensions/saxon644.jar"
	fi
	;;
   643)	SAXON="/usr/local/java/saxon-6.4.3/saxon.jar"
	SAXON_DEBUG="/usr/local/java/saxon-6.4.3/.classes"
	NDWEXT="/sourceforge/docbook/xsl/extensions/saxon643/.classes";
	if [ "$JAR" = "1" ]; then
	    NDWEXT="/sourceforge/docbook/xsl/extensions/saxon643.jar"
	fi
	;;
   642)	SAXON="/usr/local/java/saxon-6.4.2/saxon.jar"
	SAXON_DEBUG="/usr/local/java/saxon-6.4.2/.classes"
	NDWEXT="/sourceforge/docbook/xsl/extensions/saxon642/.classes";
	if [ "$JAR" = "1" ]; then
	    NDWEXT="/sourceforge/docbook/xsl/extensions/saxon642.jar"
	fi
	;;
   64)	SAXON="/usr/local/java/saxon-6.4/saxon.jar"
	SAXON_DEBUG="/usr/local/java/saxon-6.4/.classes"
	NDWEXT="/sourceforge/docbook/xsl/extensions/saxon64/.classes";
	if [ "$JAR" = "1" ]; then
	    NDWEXT="/sourceforge/docbook/xsl/extensions/saxon64.jar"
	fi
	;;
   63)	SAXON="/usr/local/java/saxon-6.3/saxon.jar"
	SAXON_DEBUG="/usr/local/java/saxon-6.3/.classes"
	NDWEXT="/sourceforge/docbook/xsl/extensions/saxon63/.classes";
	if [ "$JAR" = "1" ]; then
	    NDWEXT="/sourceforge/docbook/xsl/extensions/saxon63.jar"
	fi
	;;
  622)	SAXON="/usr/local/java/saxon-6.2.2/saxon.jar"
	SAXON_DEBUG="/usr/local/java/saxon-6.2.2/.classes"
	NDWEXT="/sourceforge/docbook/xsl/extensions/saxon61/.classes";
	if [ "$JAR" = "1" ]; then
	    NDWEXT="/sourceforge/docbook/xsl/extensions/saxon61.jar"
	fi
	;;
  621)	SAXON="/usr/local/java/saxon-6.2.1/saxon.jar"
	SAXON_DEBUG="/usr/local/java/saxon-6.2.1/.classes"
	NDWEXT="/sourceforge/docbook/xsl/extensions/saxon61/.classes";
	if [ "$JAR" = "1" ]; then
	    NDWEXT="/sourceforge/docbook/xsl/extensions/saxon61.jar"
	fi
	;;
   62)	SAXON="/usr/local/java/saxon-6.2/saxon.jar"
	SAXON_DEBUG="/usr/local/java/saxon-6.2/.classes"
	NDWEXT="/sourceforge/docbook/xsl/extensions/saxon61/.classes";
	if [ "$JAR" = "1" ]; then
	    NDWEXT="/sourceforge/docbook/xsl/extensions/saxon61.jar"
	fi
	;;
   61)	SAXON="/usr/local/java/saxon-6.1/saxon.jar"
	SAXON_DEBUG="/usr/local/java/saxon-6.1/.classes"
	NDWEXT="/sourceforge/docbook/xsl/extensions/saxon61/.classes";
	if [ "$JAR" = "1" ]; then
	    NDWEXT="/sourceforge/docbook/xsl/extensions/saxon61.jar"
	fi
	;;
    6)	SAXON="/usr/local/java/saxon-6.0.2/saxon.jar"
	SAXON_DEBUG="/usr/local/java/saxon-6.0.2/.classes"
	NDWEXT="/sourceforge/docbook/xsl/extensions/saxon6/.classes";
	if [ "$JAR" = "1" ]; then
	    NDWEXT="/sourceforge/docbook/xsl/extensions/saxon6.jar"
	fi
	;;
    5)	SAXON="/usr/local/java/saxon-5.5.1/saxon.jar"
	SAXON_DEBUG="/usr/local/java/saxon-5.5.1/.classes"
	NDWEXT="/sourceforge/docbook/xsl/extensions/saxon551/.classes";
	if [ "$JAR" = "1" ]; then
	    NDWEXT="/sourceforge/docbook/xsl/extensions/saxon551.jar"
	fi
	;;
    *)	echo "Unexpected Saxon version $VERSION"
	exit
	;;
esac

if [ "$DEBUG" = "1" ]; then
  SAXON="$SAXON_DEBUG:$SAXON"
fi

JAXP="${JAXP:-/projects/sun/resolver/.classes}:"
RESOLVER="${RESOLVER:-/projects/sun/resolver/.classes}:"
XERCES="${XERCES:-/projects/apache/xml-xerces/java/build/classes}:"

CLASSPATH=$SAXON:$NDWEXT:$JAXP$RESOLVER$XERCES$CLASSPATH

#echo $CLASSPATH

if [ "$QUIET" = "0" ]; then
  echo saxon$VERSION $OUTPUT $XMLSRC $XMLSTY $@

  if [ "$MEMORY" != "" ]; then
      echo "java $MEMORY ..."
  fi
fi

TRANSFACTORY=com.icl.saxon.TransformerFactoryImpl

# Force Saxon to use a decent parser (AElfred doesn't do PEs right)
DBFACTORY=org.apache.xerces.jaxp.DocumentBuilderFactoryImpl
SPFACTORY=org.apache.xerces.jaxp.SAXParserFactoryImpl

java $MEMORY $FOO \
     -cp $CLASSPATH \
     -Djavax.xml.parsers.DocumentBuilderFactory=$DBFACTORY \
     -Djavax.xml.parsers.SAXParserFactory=$SPFACTORY \
     com.icl.saxon.StyleSheet \
     $XARG $YARG $RARG $OUTPUT $XMLSRC $XMLSTY $@

if [ $? != 0 ]; then
  echo ""
  echo FAILED
  echo ""
  exit 1
fi
