#!/bin/bash

DONE=0
VERSION=2
DEBUG=0
QUIET=0
MEMORY=""

while [ "$DONE" = "0" ]; do
    case $1 in
	-d)	DEBUG=1;
		shift;
		;;
        -m)     shift
		MEMORY="-Xmx$1";
		shift;
		;;
        -q)     shift
		QUIET=1
		;;
        -1)     shift
		VERSION=1
		;;
        -2)     shift
		VERSION=2
		;;
        -D11)   shift
		VERSION=D11
		;;
        -220)   shift
		VERSION=220
		;;
	-*)	DONE=1;
	        ;;
	*)	DONE=1
                ;;
    esac
done

JAXP="${JAXP:-/projects/sun/resolver/.classes}:"
RESOLVER="${RESOLVER:-/projects/sun/resolver/.classes}:"
XERCES="${XERCES:-/projects/apache/xml-xerces/java/build/classes}:"
NDWEXT="/sourceforge/docbook/xsl/extensions/xalan2/.classes";

if [ "$VERSION" = "1" ]; then
    RESOLVERS=
    XALANROOT="${XALANROOT:-/usr/local/java/xalan-1.2.2}"
    XALAN="$XALANROOT/bsf.jar:"
elif [ "$VERSION" = "2" ]; then
    URES="-URIRESOLVER com.sun.resolver.tools.CatalogResolver"
    ERES="-ENTITYRESOLVER com.sun.resolver.tools.CatalogResolver"
    RESOLVERS="$URES $ERES"
    XALANROOT="${XALANROOT:-/projects/apache/xml-xalan/java}";
    XALAN="$XALANROOT/build/classes:$XALANROOT/bin/bsf.jar:"
elif [ "$VERSION" = "D11" ]; then
    URES="-URIRESOLVER com.sun.resolver.tools.CatalogResolver"
    ERES="-ENTITYRESOLVER com.sun.resolver.tools.CatalogResolver"
    RESOLVERS="$URES $ERES"
    XALANROOT="/usr/local/java/xalan-j_2_2_D11/bin"
    XALAN="$XALANROOT/xalan.jar:$XALANROOT/xml.jar"
elif [ "$VERSION" = "220" ]; then
    URES="-URIRESOLVER com.sun.resolver.tools.CatalogResolver"
    ERES="-ENTITYRESOLVER com.sun.resolver.tools.CatalogResolver"
    RESOLVERS="$URES $ERES"
    XALANROOT="/usr/local/java/xalan-j_2_2_0/bin"
    XALAN="$XALANROOT/xalan.jar:$XALANROOT/xml-apis.jar"
else
    echo "Unexpected Xalan version $VERSION"
    exit 1
fi

CLASSPATH=$NDWEXT:$XALAN$JAXP$RESOLVER$XERCES$CLASSPATH

#echo $CLASSPATH

if [ "$QUIET" = "0" ]; then
    echo xalan$VERSION $@
    if [ "$MEMORY" != "" ]; then
	echo "java $MEMORY ..."
    fi
fi

# -Djavax.xml.parsers.DocumentBuilderFactory=org.apache.xerces.jaxp.DocumentBuilderFactoryImpl
# -Djavax.xml.parsers.SAXParserFactory=org.apache.xerces.jaxp.SAXParserFactoryImpl"

echo org.apache.xalan.xslt.Process $RESOLVERS $@

java $MEMORY \
 org.apache.xalan.xslt.Process $RESOLVERS $@

if [ $? != 0 ]; then
  echo ""
  echo FAILED
  echo ""
fi
