#!/bin/bash

DONE=0
VERSION=2
DEBUG=0
QUIET=0
MEMORY=""

while [ "$DONE" = "0" ]; do
    case $1 in
	-d)	DEBUG=1;
		shift;
		;;
        -m)     shift
		MEMORY="-Xmx$1";
		shift;
		;;
        -q)     shift
		QUIET=1
		;;
        -1)     shift
		VERSION=1
		;;
        -2)     shift
		VERSION=2
		;;
	-*)	DONE=1;
	        ;;
	*)	DONE=1
                ;;
    esac
done

JAXP="/usr/local/jaxp-1.1/jaxp.jar:/usr/local/jaxp-1.1/crimson.jar"
SUN="/projects/sun/resolver/.classes"
NDWEXT="/sourceforge/docbook/xsl/extensions/xalan2/.classes";

if [ "$VERSION" = "1" ]; then
    RESOLVERS=
    XALANROOT="/usr/local/java/xalan-1.2.2"
    CLASSPATH="$NDWEXT:$JAXP:$XALANROOT/xalan.jar:$XALANROOT/xerces.jar:$XALANROOT/bsf.jar"
elif [ "$VERSION" = "2" ]; then
    URES="-URIRESOLVER com.sun.resolver.tools.CatalogResolver"
    ERES="-ENTITYRESOLVER com.sun.resolver.tools.CatalogResolver"
    RESOLVERS="$URES $ERES"
    XALANROOT="/projects/apache/xml-xalan/java";
    XALAN="$XALANROOT/build/classes"
    XERCESROOT="/projects/apache/xml-xerces/java"
    XERCES="$XERCESROOT/build/classes"
    XJARS="$XALANROOT/bin/bsf.jar:$XALANROOT/bin/xerces.jar"
    CLASSPATH=$NDWEXT:$JAXP:$XALAN:$XJARS:$SUN:$XERCES:$CLASSPATH
else
    echo "Unexpected Xalan version $VERSION"
    exit 1
fi

#echo $CLASSPATH

if [ "$QUIET" = "0" ]; then
    echo xalan$VERSION $@
    if [ "$MEMORY" != "" ]; then
	echo "java $MEMORY ..."
    fi
fi

java $MEMORY \
 org.apache.xalan.xslt.Process $RESOLVERS $@

if [ $? != 0 ]; then
  echo ""
  echo FAILED
  echo ""
fi


