#!/bin/bash

# This shell script will definitely need to be hacked to run on your system!
#
# Usage: xjparse [opts] src.xml

JAXP="${JAXP:-/usr/local/jaxp-1.1/jaxp.jar}:"
RESOLVER="${RESOLVER:-/projects/apache/xml-commons/java/build/classes}:"
XERCES="${XERCES:-/projects/apache/xml-xerces/java/build/classes}:"

CLASSPATH=$JAXP$RESOLVER$XERCES$CLASSPATH

#echo $CLASSPATH

java \
  org.apache.xml.resolver.apps.xread $*

if [ $? != 0 ]; then
  echo ""
  echo FAILED
  echo ""
  exit 1
fi
