#!/bin/bash

# USAGE:
#   xslt [-xsltproc|-xalan|-saxon]  inputfile  xslfile  outputfile  [param1=value1 [param2=value2 ...]]

PROC=saxon

case $1 in
    -xsltproc)	PROC=xsltproc;
		shift;
		;;
    -xalan)	PROC=xalan
		shift;
		;;
    -saxon)	PROC=saxon
		shift;
		;;
esac

exec `dirname $0`/$PROC "$@"



