<?xml version="1.0"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:saxon="http://icl.com/saxon"
                extension-element-prefixes="saxon"
                version="1.0">

<xsl:output method="xml" encoding="US-ASCII"/>

<xsl:strip-space elements="localization"/>

<xsl:template match="i18n">
  <xsl:apply-templates select="localization"/>
</xsl:template>

<xsl:template match="locale">
  <xsl:variable name="filename">
    <xsl:value-of select="@language"/>
    <xsl:text>.xml</xsl:text>
  </xsl:variable>

  <xsl:message><xsl:value-of select="$filename"/></xsl:message>

  <saxon:output method="xml" encoding="US-ASCII" href="{$filename}">
    <xsl:text>&#10;</xsl:text>
    <localization language="{@language}">
      <xsl:text>&#10;</xsl:text>
      <xsl:comment> This file is generated automatically. </xsl:comment>
      <xsl:text>&#10;</xsl:text>
      <xsl:comment> Do not edit this file by hand! </xsl:comment>

      <xsl:apply-templates/>
    </localization>
    <xsl:text>&#10;</xsl:text>
  </saxon:output>
</xsl:template>

<xsl:template match="gentext|dingbat|xref">
  <xsl:element name="{name(.)}">
    <xsl:copy-of select="@*"/>
    <xsl:apply-templates/>
  </xsl:element>
</xsl:template>

</xsl:stylesheet>
