#!/bin/sh
# vim: number

# docbook-build - Build script for generating DocBook project snapshots
# $Id$

# fail if no CLASSPATH set
if [ -z "$CLASSPATH" ]; then
  cat <<- EOF
`basename $0`: error: CLASSPATH not set. Stopping.

Before invoking `basename $0`, you must set the Java CLASSPATH
environment variable in the environment from which the script
runs, and it must contain absolute pathnames for the following:

  - Saxon or Xalan2 jar file or classes
  - Xerces jar file(s) or classes
  - Apache XML Commons Resolver jar file or classes
  - directory containing CatalogManager.properties file
EOF
  exit 1
fi

# fail if no DOCBOOK_SVN set
if [ -z "$DOCBOOK_SVN" ]; then
  cat <<- EOF
`basename $0`: error: DOCBOOK_SVN not set. Stopping.

Before invoking `basename $0`, you must set the DOCBOOK_SVN
environment variable in the environment from which the script
runs. The value of DOCBOOK_SVN should be the absolute path to the
base of a DocBook Project Subversion working directory that
contains the various DocBook Project modules; that is, such that
the modules can be found in \$DOCBOOK_SVN/xsl, etc.
EOF
  exit 1
fi

umask 002
# set up some defaults
ENGINE=xsltproc
PDF_MAKER=dblatex
TAR=tar
TARFLAGS=P
ZIPTARG=zip
SITEUSER=`whoami`
SITEBASE=/home/groups/d/do/docbook/htdocs/snapshots
SITEHOST=docbook.sourceforge.net
RELEASEVERSION=snapshot
if [ -z "$TMP" ]; then
  TMP=/tmp
fi
# default timeout waiting for lock file to clear is 1200 seconds (20 mins)
LOCK_TIMEOUT=1200

usage="Usage:

  `basename $0` [-a ADDEDSUFFIX] [-b BASEDIR] [-d DOMAIN]
                [-e ENGINENAME] [-f FORMATTER] [-l LOGDIR]
                [-p PATH] [-r] [-s] [-t TMPDIR] [-u USER]
                [-v VERSION] [-x ZIPTARG] [-z ZONE] DISTRO...

"
opts_admon="Type '`basename $0` -h' for details about options.
"

help="
Options:

  -a ADDEDSUFFIX
     Specifies a suffix for any additional packages that are built
     along with the package for this distro. For example, in the
     cause of the docbook-xsl package, we also build docbook-xsl-ns,
     using \"-a ns\"

  -b BASEDIR
     Specifies the location of the base directory containing the
     SVN working directories for modules from the DocBook project
     (directory containing 'xsl', 'dsssl', 'slides', etc. subdirs)
     Default: value of the DOCBOOK_SVN environment variable, if
     set; otherwise, the directory from which the script is run.

  -d DOMAIN
     Specifies the remote host (domain) to which the snaphost is
     uploaded. Default: 'docbook.sourceforge.net'

  -e ENGINENAME
     Specifies which XSLT engine to use. Default: xsltproc

  -f FORMATTER
     Specifies which formatter to use for generating the PDF
     version of the release notes for the distribution.
     Default: dblatex

  -l LOGDIR
     Specifies the directory to which the script redirects its
     standard output and standard error.
     Default: none -- if not set, stdout and stderr are not
     redirected to a log file.

  -p PATH
     Specifies the upload path on the remote host.
     Default: '/home/groups/d/do/docbook/htdocs/snapshots'

  -r
     If specified, read commit message from standard input.

  -s
     If specified, scp the distro to upload site (after tar/zipping).

  -t TMPDIR
     Specifies the directory to which the script writes temporary
     files. Default: /tmp

  -u USER
     Specifies the (Sourceforge) username with which to upload the
     snapshot to the target (Sourceforge) website.
     Default: Username found in SVN/Root in working directory, if
     found; otherwise, local username.

  -v VERSION
     Specifies the version name to put on the build.
     Default: 'snapshot'

  -x ZIPTARG
     Specifies name of the target to use for building compressed
     package file. Default: 'zip'

  -z ZONE
     Specifies timezone to use for date/time stamps.
     Default: none -- if not set, 'date' uses timezone configured
     on local machine.

  DISTRO...
     Space-separated list of distros to build (e.g. 'xsl dsssl')

"
while getopts ":a:b:e:f:d:hl:p:rst:u:v:x:z:" opt; do
  case $opt in
    r  ) # parse commit message
         while read -r LINE
         do
          if echo $LINE | grep "^Subject: " >/dev/null; then
            CHANGEPATH=$(echo $LINE | sed 's/^Subject: SF.net SVN: docbook: \[[^\]\+\]\(.\+\)$/\1/')
            REVISION=$(echo $LINE | sed 's/^Subject: SF.net SVN: docbook: \[\([^\]\+\)\].\+$/\1/')
            break
          fi
         done ;;
    a  ) ADDEDSUFFIX=$OPTARG ;;
    b  ) BUILDDIR=$OPTARG ;;
    e  ) ENGINE=$OPTARG ;;
    f  ) PDF_MAKER=$OPTARG ;;
    l  ) LOGDIR=$OPTARG ;;
    t  ) TMP=$OPTARG ;;
    v  ) RELEASEVERSION=$OPTARG ;;
    u  ) SITEUSER=$OPTARG ;;
    d  ) SITEHOST=$OPTARG ;;
    p  ) SITEBASE=$OPTARG ;;
    s  ) UPLOAD="yes" ;;
    x  ) ZIPTARG=$OPTARG ;;
    z  ) TZ=$OPTARG
         alias date="TZ=$TZ date" ;;
    h  ) printf "$usage"
         printf "$help"
         exit 0 ;;
    \? ) printf "$usage"
         printf "$opts_admon"
         exit 1 ;;
  esac
done

shift $(($OPTIND - 1))

if [ -z "$BUILDDIR"  ]; then
  BUILDDIR=`pwd`
fi
cd $BUILDDIR

DISTROS="$@"

if [ -z "$DISTROS" ]; then
  echo
  echo "`basename $0`: error: No DISTROS specified. Stopping."
  echo
  printf "$usage"
  printf "$opts_admon"
  exit 1;
else
  for DISTRO in $DISTROS; do
    lock_timer=0
    # wait for lock file (if any) to clear
    printf "Waiting for lock file to clear..." 1>&2
    while [ -f $TMP/docbook-*-$RELEASEVERSION.lock ]; do
      if [ $lock_timer = $LOCK_TIMEOUT ]; then
        # time out after reaching $LOCK_TIMEOUT seconds
        # default is 1200 seconds (20 minutes)
        echo
        printf "Timed out after $LOCK_TIMEOUT seconds waiting for lock file to clear.\n"
        echo "You probably have a stale $TMP/docbook-$DISTRO-$RELEASEVERSION.lock file that you need to delete."
        exit 1
      fi
      printf "." 1>&2
      sleep 1
      let lock_timer=$lock_timer+1
    done 
    printf "Done.\n" 1>&2

    printf "Doing some initialization..." 1>&2
    # create new lock file
    touch $TMP/docbook-$DISTRO-$RELEASEVERSION.lock
    # remove old log file, if any
    rm -f $LOGDIR/docbook-$DISTRO-$RELEASEVERSION.log.tmp

    DATE=`date +%Y-%m-%d`
    TIME=`date '+%H%M'`
    ZONE=`date '+%Z'`

    #if [ -f $DISTRO/CVS/Root ]; then
    #  CVSROOT=`cat $DISTRO/CVS/Root`
    #  export CVSROOT
    #  CVSUSER=`sed 's/^:.\+:\([^@]\+\)@.\+$/\1/' $DISTRO/CVS/Root`
    #  if [ "$CVSUSER" != "anonymous" ]; then
    #    CVS_RSH=ssh
    #    export CVS_RSH
    #  fi
    #  if [ -z "$OVERRIDE_CVSUSER" ]; then
    #    # if no value for USER has been specified via -u option, set
    #    # SITEUSER for ssh uploads to same value as CVSUSER
    #    SITEUSER=$CVSUSER
    #  fi
    #fi
    #rm -f $DISTRO/LatestTag
    rm -f $DISTRO/VERSION
    svn update $DISTRO/VERSION 1>/dev/null 2>&1

    printf "." 1>&2

    # replace the current fm:Version value with the snapshot number
    cp -p $DISTRO/VERSION $DISTRO/VERSION.tmp
    # FIXME: we really should be doing this using a modifiled XSLT identity
    # transform, but anyway, this works OK for now...
    sed "s/Version>.\+</Version>$RELEASEVERSION\_$REVISION\</" $DISTRO/VERSION.tmp > $DISTRO/VERSION
    rm $DISTRO/VERSION.tmp
    printf "Done.\n" 1>&2

    # start re-directing stout and stderr to log file (if logging enabled)
    if [ $LOGDIR ]; then
      echo "Logging all further output to $LOGDIR/docbook-$DISTRO-$RELEASEVERSION.log.tmp"
      exec 1> $LOGDIR/docbook-$DISTRO-$RELEASEVERSION.log.tmp
      exec 2>&1
    fi

    date
    echo
    # echo selected variables
    set | grep "^CHANGE\|REVISION"
    echo

    echo "Running svn update in gentext and $DISTRO working directories..."
    svn cleanup
    svn update gentext || exit 1
    svn update $DISTRO || exit 1
    echo

    echo
    date
    echo "Building $DISTRO distribution..."
    echo

    make distrib -C $DISTRO XSLT="$DOCBOOK_SVN/buildtools/xslt -$ENGINE" PDF_MAKER=$PDF_MAKER

    cat <<- EOF > HEADER.txt
The snapshot for a particular distribution is re-built automatically each time
a change is checked into the SVN source tree for the distribution. The most
recent build was of the "$DISTRO" distribution, for revision $REVISION,
on $DATE at $TIME $ZONE.

These snapshots are intended for testing purposes only and otherwise come with
no guarantees. Any of them may in fact be broken at any given time.
EOF

    if [ "$UPLOAD" = "yes" ]; then

    make $ZIPTARG -C $DISTRO ZIPVER=$RELEASEVERSION TMP=$TMP XSLT="$DOCBOOK_SVN/buildtools/xslt -$ENGINE" PDF_MAKER=$PDF_MAKER || exit 1

    cat <<- EOF > $TMP/line.tmp

--------------------------------------------------------------------------------
Latest Changes:
--------------------------------------------------------------------------------

EOF
    svn cleanup && svn update && svn log --verbose --limit 200 > LatestChanges

    cat HEADER.txt $TMP/line.tmp LatestChanges > README.txt
    rm $TMP/line.tmp

    # Uncompress tarball to local mirror directory.
    # Previously, we uploaded and untarred it to the remote host
    # (sourceforge.net web server), but 100Mb quota limit at
    # Sourceforge made that a not-very-efficient use of the
    # project disk space
    cp $TMP/docbook*-$DISTRO*$RELEASEVERSION.tar.bz2 $SITEBASE
    (umask 002; \
    cd $SITEBASE; \
    rm -f docbook-$DISTRO-$RELEASEVERSION.log; \
    rm -rf $DISTRO; \
    rm -rf $DISTRO-$ADDEDSUFFIX; \
    for tarball in docbook-$DISTRO*$RELEASEVERSION.tar.bz2; do \
    cat $tarball | bunzip2 | \
    (cd $TMP; $TAR xf$TARFLAGS -); \
    done; \
    mkdir $DISTRO; \
    cp -pR $TMP/docbook-$DISTRO-$RELEASEVERSION/* $DISTRO; \
    if [ -d $TMP/docbook-$DISTRO-$$RELEASEVERSION ]; then \
    cp -pR $TMP/docbook-$DISTRO-$ADDEDSUFFIX-$RELEASEVERSION/* $DISTRO-$ADDEDSUFFIX; \
    fi; \
    )

    scp \
      $TMP/docbook*-$DISTRO*$RELEASEVERSION.zip \
      README.txt \
      LatestChanges \
      $SITEUSER@$SITEHOST:$SITEBASE

    rm -rf $TMP/docbook-$DISTRO*$RELEASEVERSION.tar.bz2
    rm -rf $TMP/docbook-$DISTRO*$RELEASEVERSION.tar.gz
    rm -rf $TMP/docbook-$DISTRO*$RELEASEVERSION.zip
    rm -rf $TMP/docbook-$DISTRO-$RELEASEVERSION
    rm -rf $TMP/docbook-$DISTRO-$ADDEDSUFFIX-$RELEASEVERSION

    rm -f $DISTRO/LatestChanges HEADER.txt README.txt LatestChanges

    date

    if [ -f $LOGDIR/docbook-$DISTRO-$RELEASEVERSION.log.tmp ]; then
      # filter raw log and copy to site
      cat $LOGDIR/docbook-$DISTRO-$RELEASEVERSION.log.tmp \
      | grep -v '^cvs log: \|cvs update\|^tar: \|^tar \|^  adding: \|^find \|^cd \|rm \|^mkdir \|^touch \|cvs2log\|mergechangelogs\|\s*(\|^  inflating: docbook-\|^ extracting: docbook-\|^docbook-' \
        > $LOGDIR/docbook-$DISTRO-$RELEASEVERSION.log
      scp $LOGDIR/docbook-$DISTRO-$RELEASEVERSION.log $SITEUSER@$SITEHOST:$SITEBASE
    fi
    ssh -l $SITEUSER $SITEHOST "(cd $SITEBASE; chmod 664 *.zip *.log; touch $DISTRO)"
    fi

    # set up the e-mail message headers for buildbot message
    cat <<- EOF > $TMP/docbook-$DISTRO-$RELEASEVERSION-message.txt
From: snapshot buildbot <smith@sideshowbarker.net>
To: Michael(tm) Smith <smith@sideshowbarker.net>
Subject: snapshot $REVISION

EOF

    # run buildcheck and copy the output to the beginning of the
    # buildbot message
    $DOCBOOK_SVN/buildtools/build-check $LOGDIR/docbook-$DISTRO-$RELEASEVERSION.log.tmp >> $TMP/docbook-$DISTRO-$RELEASEVERSION-message.txt
    # copy the entire log file to the buildbot message
    cat $LOGDIR/docbook-$DISTRO-$RELEASEVERSION.log.tmp >> $TMP/docbook-$DISTRO-$RELEASEVERSION-message.txt
    echo >> $TMP/docbook-$DISTRO-$RELEASEVERSION-message.txt
    echo "buildcheck output:" >> $TMP/docbook-$DISTRO-$RELEASEVERSION-message.txt

    # send the buildbot message
    /usr/sbin/sendmail -f smith@sideshowbarker.net smith@sideshowbarker.net < $TMP/docbook-$DISTRO-$RELEASEVERSION-message.txt

    rm -f $LOGDIR/docbook-$DISTRO-$RELEASEVERSION.log
    rm -f $TMP/docbook-$DISTRO-$RELEASEVERSION.lock

    cd -
  done
fi
