#!/bin/sh
# $Id$

# release-announce - send DocBook Project release announcements

# Usage:
# release-announce TITLE VERSION RECIPIENTS < messageBodyFile
#   or
# cat messageBodyFile | release-announce TITLE VERSION RECIPIENTS 
#
# e.g.,
#   release-announce XSL Stylesheets 1.73.0 docbook-apps@lists.oasis-open.org < .announcement-text

title=$1
version=$2
recipients=$3
sender=docbook-dev@xml-doc.org
tempfile=/tmp/announcement-message-body.txt
releasenotesfilename=RELEASE-NOTES-PARTIAL.txt

rm -f $tempfile

cat <<- EOF > $tempfile
From: DocBook Project <$sender>
To: $recipients
Subject: ANNOUNCE: DocBook $title $version released

EOF

# read in annoucement text
while read line
do
  # substitute actual version no. where needed, append to message body
  echo $line | sed "s/@@version@@/$version/" >> $tempfile
done

# add a blank line to separate announcement header and text from
# appended release-notes content
echo >> $tempfile

cat $tempfile $releasenotesfilename | sendmail -v -f $sender $recipients
