#!/bin/sh
# $Id$

# release-announce - send DocBook Project release announcements

# Usage:
# release-announce TITLE VERSION MESSAGE CHANGES RECIPIENTS
#
# e.g.,
#  release-announce "XSL Stylesheets" 1.73.0 \
#    .announcement-text \
#    RELEASE-NOTES-PARTIAL.txt \
#    docbook-apps@lists.oasis-open.org

title=$1
version=$2
message=$3
changesfile=$4
recipients=$5
sender=docbook-dev@xml-doc.org
tempfile=/tmp/announcement-message-body.txt

rm -f $tempfile

cat <<- EOF > $tempfile
From: DocBook Project <$sender>
To: $recipients
Subject: ANNOUNCE: DocBook $title $version released

EOF

# append announcement boilerplate text, substituting actual version
# number where needed
sed "s/@@version@@/$version/" < $message >> $tempfile

# add a blank line to separate announcement header and text from
# appended release-notes content
echo >> $tempfile

# append the current list of changes
cat $changesfile >> $tempfile

# e-mail the actual announcement
cat $tempfile | sendmail -v -f $sender $recipients
