# Makefile.incl gets included by makefiles in all subdirs

all: $(HTMLFILES)

%.html : %.xml $(JREFHTML)
	$(XSLT) $< $(JREFHTML) $@ $(XSLTOPT)

param.html: docparam.xml
	$(XSLT) $< ../../docsrc/clrefentry.xsl $(XSLTOPT)
	touch param.html

clean:
	$(RM) $(HTMLFILES)
	$(RM) *.html
