;;; dbk-xsldir.el --- DocBook XSLT stylesheets directory contents
;; for DocBook XSLT stylesheets version 1.64.0
;; Revision: $Revision$
;; Date: $Date$
;; RCS Id: $Id$

(defvar docbook-menu-xsl-distro
  (list "DocBook XSL: Stylesheet Distribution"
	(list "common"
	      ["ChangeLog" (find-file (concat docbook-menu-xsl-dir "/common/ChangeLog")) t]
	      ["af.xml" (find-file (concat docbook-menu-xsl-dir "/common/af.xml")) t]
	      ["ar.xml" (find-file (concat docbook-menu-xsl-dir "/common/ar.xml")) t]
	      ["bg.xml" (find-file (concat docbook-menu-xsl-dir "/common/bg.xml")) t]
	      ["bn.xml" (find-file (concat docbook-menu-xsl-dir "/common/bn.xml")) t]
	      ["ca.xml" (find-file (concat docbook-menu-xsl-dir "/common/ca.xml")) t]
	      ["common.xsl" (find-file (concat docbook-menu-xsl-dir "/common/common.xsl")) t]
	      ["cs.xml" (find-file (concat docbook-menu-xsl-dir "/common/cs.xml")) t]
	      ["da.xml" (find-file (concat docbook-menu-xsl-dir "/common/da.xml")) t]
	      ["de.xml" (find-file (concat docbook-menu-xsl-dir "/common/de.xml")) t]
	      ["el.xml" (find-file (concat docbook-menu-xsl-dir "/common/el.xml")) t]
	      ["en.xml" (find-file (concat docbook-menu-xsl-dir "/common/en.xml")) t]
	      ["es.xml" (find-file (concat docbook-menu-xsl-dir "/common/es.xml")) t]
	      ["et.xml" (find-file (concat docbook-menu-xsl-dir "/common/et.xml")) t]
	      ["eu.xml" (find-file (concat docbook-menu-xsl-dir "/common/eu.xml")) t]
	      ["fi.xml" (find-file (concat docbook-menu-xsl-dir "/common/fi.xml")) t]
	      ["fr.xml" (find-file (concat docbook-menu-xsl-dir "/common/fr.xml")) t]
	      ["gentext.xsl" (find-file (concat docbook-menu-xsl-dir "/common/gentext.xsl")) t]
	      ["he.xml" (find-file (concat docbook-menu-xsl-dir "/common/he.xml")) t]
	      ["hr.xml" (find-file (concat docbook-menu-xsl-dir "/common/hr.xml")) t]
	      ["hu.xml" (find-file (concat docbook-menu-xsl-dir "/common/hu.xml")) t]
	      ["id.xml" (find-file (concat docbook-menu-xsl-dir "/common/id.xml")) t]
	      ["it.xml" (find-file (concat docbook-menu-xsl-dir "/common/it.xml")) t]
	      ["ja.xml" (find-file (concat docbook-menu-xsl-dir "/common/ja.xml")) t]
	      ["ko.xml" (find-file (concat docbook-menu-xsl-dir "/common/ko.xml")) t]
	      ["l10n.dtd" (find-file (concat docbook-menu-xsl-dir "/common/l10n.dtd")) t]
	      ["l10n.xml" (find-file (concat docbook-menu-xsl-dir "/common/l10n.xml")) t]
	      ["l10n.xsl" (find-file (concat docbook-menu-xsl-dir "/common/l10n.xsl")) t]
	      ["la.xml" (find-file (concat docbook-menu-xsl-dir "/common/la.xml")) t]
	      ["labels.xsl" (find-file (concat docbook-menu-xsl-dir "/common/labels.xsl")) t]
	      ["lt.xml" (find-file (concat docbook-menu-xsl-dir "/common/lt.xml")) t]
	      ["nl.xml" (find-file (concat docbook-menu-xsl-dir "/common/nl.xml")) t]
	      ["nn.xml" (find-file (concat docbook-menu-xsl-dir "/common/nn.xml")) t]
	      ["no.xml" (find-file (concat docbook-menu-xsl-dir "/common/no.xml")) t]
	      ["pi.xsl" (find-file (concat docbook-menu-xsl-dir "/common/pi.xsl")) t]
	      ["pl.xml" (find-file (concat docbook-menu-xsl-dir "/common/pl.xml")) t]
	      ["pt.xml" (find-file (concat docbook-menu-xsl-dir "/common/pt.xml")) t]
	      ["pt_br.xml" (find-file (concat docbook-menu-xsl-dir "/common/pt_br.xml")) t]
	      ["ro.xml" (find-file (concat docbook-menu-xsl-dir "/common/ro.xml")) t]
	      ["ru.xml" (find-file (concat docbook-menu-xsl-dir "/common/ru.xml")) t]
	      ["sk.xml" (find-file (concat docbook-menu-xsl-dir "/common/sk.xml")) t]
	      ["sl.xml" (find-file (concat docbook-menu-xsl-dir "/common/sl.xml")) t]
	      ["sr.xml" (find-file (concat docbook-menu-xsl-dir "/common/sr.xml")) t]
	      ["subtitles.xsl" (find-file (concat docbook-menu-xsl-dir "/common/subtitles.xsl")) t]
	      ["sv.xml" (find-file (concat docbook-menu-xsl-dir "/common/sv.xml")) t]
	      ["table.xsl" (find-file (concat docbook-menu-xsl-dir "/common/table.xsl")) t]
	      ["targetdatabase.dtd" (find-file (concat docbook-menu-xsl-dir "/common/targetdatabase.dtd")) t]
	      ["targets.xsl" (find-file (concat docbook-menu-xsl-dir "/common/targets.xsl")) t]
	      ["th.xml" (find-file (concat docbook-menu-xsl-dir "/common/th.xml")) t]
	      ["titles.xsl" (find-file (concat docbook-menu-xsl-dir "/common/titles.xsl")) t]
	      ["tr.xml" (find-file (concat docbook-menu-xsl-dir "/common/tr.xml")) t]
	      ["uk.xml" (find-file (concat docbook-menu-xsl-dir "/common/uk.xml")) t]
	      ["vi.xml" (find-file (concat docbook-menu-xsl-dir "/common/vi.xml")) t]
	      ["xh.xml" (find-file (concat docbook-menu-xsl-dir "/common/xh.xml")) t]
	      ["zh_cn.xml" (find-file (concat docbook-menu-xsl-dir "/common/zh_cn.xml")) t]
	      ["zh_tw.xml" (find-file (concat docbook-menu-xsl-dir "/common/zh_tw.xml")) t]
	      )
	(list "eclipse"
	      ["ChangeLog" (find-file (concat docbook-menu-xsl-dir "/eclipse/ChangeLog")) t]
	      ["eclipse.xsl" (find-file (concat docbook-menu-xsl-dir "/eclipse/eclipse.xsl")) t]
	      )
	(list "extensions"
	      (list "doc"
		    (list "saxon5"
			  (list "com"
				(list "nwalsh"
				      (list "saxon"
					    ["CVS.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon5/com/nwalsh/saxon/CVS.html")) t]
					    ["Callout.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon5/com/nwalsh/saxon/Callout.html")) t]
					    ["Driver.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon5/com/nwalsh/saxon/Driver.html")) t]
					    ["Text.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon5/com/nwalsh/saxon/Text.html")) t]
					    ["TextFactory.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon5/com/nwalsh/saxon/TextFactory.html")) t]
					    ["Verbatim.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon5/com/nwalsh/saxon/Verbatim.html")) t]
					    ["package-frame.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon5/com/nwalsh/saxon/package-frame.html")) t]
					    ["package-summary.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon5/com/nwalsh/saxon/package-summary.html")) t]
					    ["package-tree.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon5/com/nwalsh/saxon/package-tree.html")) t]
					    )
				      )
				)
			  ["deprecated-list.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon5/deprecated-list.html")) t]
			  ["help-doc.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon5/help-doc.html")) t]
			  ["index-all.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon5/index-all.html")) t]
			  ["index.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon5/index.html")) t]
			  ["overview-tree.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon5/overview-tree.html")) t]
			  ["package-list" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon5/package-list")) t]
			  ["packages.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon5/packages.html")) t]
			  ["serialized-form.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon5/serialized-form.html")) t]
			  ["stylesheet.css" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon5/stylesheet.css")) t]
			  )
		    (list "saxon6"
			  (list "com"
				(list "nwalsh"
				      (list "saxon6"
					    ["CVS.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon6/com/nwalsh/saxon6/CVS.html")) t]
					    ["CalloutEmitter.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon6/com/nwalsh/saxon6/CalloutEmitter.html")) t]
					    ["CopyEmitter.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon6/com/nwalsh/saxon6/CopyEmitter.html")) t]
					    ["LineCountEmitter.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon6/com/nwalsh/saxon6/LineCountEmitter.html")) t]
					    ["NumberLinesEmitter.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon6/com/nwalsh/saxon6/NumberLinesEmitter.html")) t]
					    ["Table.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon6/com/nwalsh/saxon6/Table.html")) t]
					    ["Text.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon6/com/nwalsh/saxon6/Text.html")) t]
					    ["TextFactory.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon6/com/nwalsh/saxon6/TextFactory.html")) t]
					    ["Verbatim.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon6/com/nwalsh/saxon6/Verbatim.html")) t]
					    ["package-frame.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon6/com/nwalsh/saxon6/package-frame.html")) t]
					    ["package-summary.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon6/com/nwalsh/saxon6/package-summary.html")) t]
					    ["package-tree.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon6/com/nwalsh/saxon6/package-tree.html")) t]
					    )
				      )
				)
			  ["deprecated-list.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon6/deprecated-list.html")) t]
			  ["help-doc.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon6/help-doc.html")) t]
			  ["index-all.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon6/index-all.html")) t]
			  ["index.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon6/index.html")) t]
			  ["overview-tree.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon6/overview-tree.html")) t]
			  ["package-list" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon6/package-list")) t]
			  ["packages.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon6/packages.html")) t]
			  ["serialized-form.html" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon6/serialized-form.html")) t]
			  ["stylesheet.css" (find-file (concat docbook-menu-xsl-dir "/extensions/doc/saxon6/stylesheet.css")) t]
			  )
		    )
	      (list "saxon643"
		    (list "com"
			  (list "nwalsh"
				(list "saxon"
				      ["CVS.java" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon643/com/nwalsh/saxon/CVS.java")) t]
				      ["Callout.java" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon643/com/nwalsh/saxon/Callout.java")) t]
				      ["CalloutEmitter.java" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon643/com/nwalsh/saxon/CalloutEmitter.java")) t]
				      ["ChangeLog" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon643/com/nwalsh/saxon/ChangeLog")) t]
				      ["ColumnScanEmitter.java" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon643/com/nwalsh/saxon/ColumnScanEmitter.java")) t]
				      ["ColumnUpdateEmitter.java" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon643/com/nwalsh/saxon/ColumnUpdateEmitter.java")) t]
				      ["CopyEmitter.java" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon643/com/nwalsh/saxon/CopyEmitter.java")) t]
				      ["FormatCallout.java" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon643/com/nwalsh/saxon/FormatCallout.java")) t]
				      ["FormatGraphicCallout.java" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon643/com/nwalsh/saxon/FormatGraphicCallout.java")) t]
				      ["FormatTextCallout.java" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon643/com/nwalsh/saxon/FormatTextCallout.java")) t]
				      ["FormatUnicodeCallout.java" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon643/com/nwalsh/saxon/FormatUnicodeCallout.java")) t]
				      ["ImageIntrinsics.java" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon643/com/nwalsh/saxon/ImageIntrinsics.java")) t]
				      ["LineCountEmitter.java" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon643/com/nwalsh/saxon/LineCountEmitter.java")) t]
				      ["NumberLinesEmitter.java" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon643/com/nwalsh/saxon/NumberLinesEmitter.java")) t]
				      ["Table.java" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon643/com/nwalsh/saxon/Table.java")) t]
				      ["Text.java" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon643/com/nwalsh/saxon/Text.java")) t]
				      ["TextFactory.java" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon643/com/nwalsh/saxon/TextFactory.java")) t]
				      ["UnwrapLinks.java" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon643/com/nwalsh/saxon/UnwrapLinks.java")) t]
				      ["UnwrapLinksEmitter.java" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon643/com/nwalsh/saxon/UnwrapLinksEmitter.java")) t]
				      ["Verbatim.java" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon643/com/nwalsh/saxon/Verbatim.java")) t]
				      ["package.html" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon643/com/nwalsh/saxon/package.html")) t]
				      )
				)
			  )
		    ["ChangeLog" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon643/ChangeLog")) t]
		    ["prj.el" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon643/prj.el")) t]
		    )
	      (list "xalan2"
		    (list "com"
			  (list "nwalsh"
				(list "xalan"
				      ["CVS.java" (find-file (concat docbook-menu-xsl-dir "/extensions/xalan2/com/nwalsh/xalan/CVS.java")) t]
				      ["Callout.java" (find-file (concat docbook-menu-xsl-dir "/extensions/xalan2/com/nwalsh/xalan/Callout.java")) t]
				      ["ChangeLog" (find-file (concat docbook-menu-xsl-dir "/extensions/xalan2/com/nwalsh/xalan/ChangeLog")) t]
				      ["FormatCallout.java" (find-file (concat docbook-menu-xsl-dir "/extensions/xalan2/com/nwalsh/xalan/FormatCallout.java")) t]
				      ["FormatDingbatCallout.java" (find-file (concat docbook-menu-xsl-dir "/extensions/xalan2/com/nwalsh/xalan/FormatDingbatCallout.java")) t]
				      ["FormatGraphicCallout.java" (find-file (concat docbook-menu-xsl-dir "/extensions/xalan2/com/nwalsh/xalan/FormatGraphicCallout.java")) t]
				      ["FormatTextCallout.java" (find-file (concat docbook-menu-xsl-dir "/extensions/xalan2/com/nwalsh/xalan/FormatTextCallout.java")) t]
				      ["FormatUnicodeCallout.java" (find-file (concat docbook-menu-xsl-dir "/extensions/xalan2/com/nwalsh/xalan/FormatUnicodeCallout.java")) t]
				      ["Func.java" (find-file (concat docbook-menu-xsl-dir "/extensions/xalan2/com/nwalsh/xalan/Func.java")) t]
				      ["ImageIntrinsics.java" (find-file (concat docbook-menu-xsl-dir "/extensions/xalan2/com/nwalsh/xalan/ImageIntrinsics.java")) t]
				      ["Params.java" (find-file (concat docbook-menu-xsl-dir "/extensions/xalan2/com/nwalsh/xalan/Params.java")) t]
				      ["Table.java" (find-file (concat docbook-menu-xsl-dir "/extensions/xalan2/com/nwalsh/xalan/Table.java")) t]
				      ["Text.java" (find-file (concat docbook-menu-xsl-dir "/extensions/xalan2/com/nwalsh/xalan/Text.java")) t]
				      ["Verbatim.java" (find-file (concat docbook-menu-xsl-dir "/extensions/xalan2/com/nwalsh/xalan/Verbatim.java")) t]
				      ["package.html" (find-file (concat docbook-menu-xsl-dir "/extensions/xalan2/com/nwalsh/xalan/package.html")) t]
				      )
				)
			  )
		    ["ChangeLog" (find-file (concat docbook-menu-xsl-dir "/extensions/xalan2/ChangeLog")) t]
		    )
	      (list "xsltproc"
		    (list "python"
			  ["ChangeLog" (find-file (concat docbook-menu-xsl-dir "/extensions/xsltproc/python/ChangeLog")) t]
			  ["README" (find-file (concat docbook-menu-xsl-dir "/extensions/xsltproc/python/README")) t]
			  ["cwtest.xml" (find-file (concat docbook-menu-xsl-dir "/extensions/xsltproc/python/cwtest.xml")) t]
			  ["cwtest.xsl" (find-file (concat docbook-menu-xsl-dir "/extensions/xsltproc/python/cwtest.xsl")) t]
			  ["docbook.py" (find-file (concat docbook-menu-xsl-dir "/extensions/xsltproc/python/docbook.py")) t]
			  ["docbook.pyc" (find-file (concat docbook-menu-xsl-dir "/extensions/xsltproc/python/docbook.pyc")) t]
			  ["xslt.py" (find-file (concat docbook-menu-xsl-dir "/extensions/xsltproc/python/xslt.py")) t]
			  )
		    )
	      ["ChangeLog" (find-file (concat docbook-menu-xsl-dir "/extensions/ChangeLog")) t]
	      ["build.xml" (find-file (concat docbook-menu-xsl-dir "/extensions/build.xml")) t]
	      ["prj.el" (find-file (concat docbook-menu-xsl-dir "/extensions/prj.el")) t]
	      ["saxon643.jar" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon643.jar")) t]
	      ["saxon644.jar" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon644.jar")) t]
	      ["saxon65.jar" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon65.jar")) t]
	      ["saxon651.jar" (find-file (concat docbook-menu-xsl-dir "/extensions/saxon651.jar")) t]
	      ["xalan2.jar" (find-file (concat docbook-menu-xsl-dir "/extensions/xalan2.jar")) t]
	      )
	(list "fo"
	      ["ChangeLog" (find-file (concat docbook-menu-xsl-dir "/fo/ChangeLog")) t]
	      ["admon.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/admon.xsl")) t]
	      ["autoidx.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/autoidx.xsl")) t]
	      ["autotoc.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/autotoc.xsl")) t]
	      ["axf.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/axf.xsl")) t]
	      ["biblio.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/biblio.xsl")) t]
	      ["block.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/block.xsl")) t]
	      ["callout.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/callout.xsl")) t]
	      ["component.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/component.xsl")) t]
	      ["division.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/division.xsl")) t]
	      ["docbook.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/docbook.xsl")) t]
	      ["ebnf.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/ebnf.xsl")) t]
	      ["fo-patch-for-fop.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/fo-patch-for-fop.xsl")) t]
	      ["fo-rtf.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/fo-rtf.xsl")) t]
	      ["fo.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/fo.xsl")) t]
	      ["footnote.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/footnote.xsl")) t]
	      ["fop.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/fop.xsl")) t]
	      ["formal.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/formal.xsl")) t]
	      ["glossary.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/glossary.xsl")) t]
	      ["graphics.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/graphics.xsl")) t]
	      ["htmltbl.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/htmltbl.xsl")) t]
	      ["index.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/index.xsl")) t]
	      ["info.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/info.xsl")) t]
	      ["inline.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/inline.xsl")) t]
	      ["keywords.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/keywords.xsl")) t]
	      ["lists.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/lists.xsl")) t]
	      ["math.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/math.xsl")) t]
	      ["pagesetup.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/pagesetup.xsl")) t]
	      ["param.ent" (find-file (concat docbook-menu-xsl-dir "/fo/param.ent")) t]
	      ["param.xml" (find-file (concat docbook-menu-xsl-dir "/fo/param.xml")) t]
	      ["param.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/param.xsl")) t]
	      ["param.xweb" (find-file (concat docbook-menu-xsl-dir "/fo/param.xweb")) t]
	      ["passivetex.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/passivetex.xsl")) t]
	      ["pdf2index" (find-file (concat docbook-menu-xsl-dir "/fo/pdf2index")) t]
	      ["pi.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/pi.xsl")) t]
	      ["profile-docbook.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/profile-docbook.xsl")) t]
	      ["qandaset.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/qandaset.xsl")) t]
	      ["refentry.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/refentry.xsl")) t]
	      ["sections.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/sections.xsl")) t]
	      ["synop.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/synop.xsl")) t]
	      ["table.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/table.xsl")) t]
	      ["task.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/task.xsl")) t]
	      ["titlepage.templates.xml" (find-file (concat docbook-menu-xsl-dir "/fo/titlepage.templates.xml")) t]
	      ["titlepage.templates.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/titlepage.templates.xsl")) t]
	      ["titlepage.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/titlepage.xsl")) t]
	      ["toc.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/toc.xsl")) t]
	      ["verbatim.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/verbatim.xsl")) t]
	      ["xep.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/xep.xsl")) t]
	      ["xref.xsl" (find-file (concat docbook-menu-xsl-dir "/fo/xref.xsl")) t]
	      )
	(list "html"
	      ["ChangeLog" (find-file (concat docbook-menu-xsl-dir "/html/ChangeLog")) t]
	      ["admon.xsl" (find-file (concat docbook-menu-xsl-dir "/html/admon.xsl")) t]
	      ["autoidx.xsl" (find-file (concat docbook-menu-xsl-dir "/html/autoidx.xsl")) t]
	      ["autotoc.xsl" (find-file (concat docbook-menu-xsl-dir "/html/autotoc.xsl")) t]
	      ["biblio.xsl" (find-file (concat docbook-menu-xsl-dir "/html/biblio.xsl")) t]
	      ["block.xsl" (find-file (concat docbook-menu-xsl-dir "/html/block.xsl")) t]
	      ["callout.xsl" (find-file (concat docbook-menu-xsl-dir "/html/callout.xsl")) t]
	      ["changebars.xsl" (find-file (concat docbook-menu-xsl-dir "/html/changebars.xsl")) t]
	      ["chunk-code.xsl" (find-file (concat docbook-menu-xsl-dir "/html/chunk-code.xsl")) t]
	      ["chunk-common.xsl" (find-file (concat docbook-menu-xsl-dir "/html/chunk-common.xsl")) t]
	      ["chunk.xsl" (find-file (concat docbook-menu-xsl-dir "/html/chunk.xsl")) t]
	      ["chunker.xsl" (find-file (concat docbook-menu-xsl-dir "/html/chunker.xsl")) t]
	      ["chunkfast.xsl" (find-file (concat docbook-menu-xsl-dir "/html/chunkfast.xsl")) t]
	      ["chunktoc.xsl" (find-file (concat docbook-menu-xsl-dir "/html/chunktoc.xsl")) t]
	      ["component.xsl" (find-file (concat docbook-menu-xsl-dir "/html/component.xsl")) t]
	      ["division.xsl" (find-file (concat docbook-menu-xsl-dir "/html/division.xsl")) t]
	      ["docbook.xsl" (find-file (concat docbook-menu-xsl-dir "/html/docbook.xsl")) t]
	      ["ebnf.xsl" (find-file (concat docbook-menu-xsl-dir "/html/ebnf.xsl")) t]
	      ["footnote.xsl" (find-file (concat docbook-menu-xsl-dir "/html/footnote.xsl")) t]
	      ["formal.xsl" (find-file (concat docbook-menu-xsl-dir "/html/formal.xsl")) t]
	      ["glossary.xsl" (find-file (concat docbook-menu-xsl-dir "/html/glossary.xsl")) t]
	      ["graphics.xsl" (find-file (concat docbook-menu-xsl-dir "/html/graphics.xsl")) t]
	      ["html-rtf.xsl" (find-file (concat docbook-menu-xsl-dir "/html/html-rtf.xsl")) t]
	      ["html.xsl" (find-file (concat docbook-menu-xsl-dir "/html/html.xsl")) t]
	      ["htmltbl.xsl" (find-file (concat docbook-menu-xsl-dir "/html/htmltbl.xsl")) t]
	      ["index.xsl" (find-file (concat docbook-menu-xsl-dir "/html/index.xsl")) t]
	      ["info.xsl" (find-file (concat docbook-menu-xsl-dir "/html/info.xsl")) t]
	      ["inline.xsl" (find-file (concat docbook-menu-xsl-dir "/html/inline.xsl")) t]
	      ["keywords.xsl" (find-file (concat docbook-menu-xsl-dir "/html/keywords.xsl")) t]
	      ["lists.xsl" (find-file (concat docbook-menu-xsl-dir "/html/lists.xsl")) t]
	      ["maketoc.xsl" (find-file (concat docbook-menu-xsl-dir "/html/maketoc.xsl")) t]
	      ["manifest.xsl" (find-file (concat docbook-menu-xsl-dir "/html/manifest.xsl")) t]
	      ["math.xsl" (find-file (concat docbook-menu-xsl-dir "/html/math.xsl")) t]
	      ["oldchunker.xsl" (find-file (concat docbook-menu-xsl-dir "/html/oldchunker.xsl")) t]
	      ["onechunk.xsl" (find-file (concat docbook-menu-xsl-dir "/html/onechunk.xsl")) t]
	      ["param.ent" (find-file (concat docbook-menu-xsl-dir "/html/param.ent")) t]
	      ["param.xml" (find-file (concat docbook-menu-xsl-dir "/html/param.xml")) t]
	      ["param.xsl" (find-file (concat docbook-menu-xsl-dir "/html/param.xsl")) t]
	      ["param.xweb" (find-file (concat docbook-menu-xsl-dir "/html/param.xweb")) t]
	      ["pi.xsl" (find-file (concat docbook-menu-xsl-dir "/html/pi.xsl")) t]
	      ["profile-chunk-code.xsl" (find-file (concat docbook-menu-xsl-dir "/html/profile-chunk-code.xsl")) t]
	      ["profile-chunk.xsl" (find-file (concat docbook-menu-xsl-dir "/html/profile-chunk.xsl")) t]
	      ["profile-docbook.xsl" (find-file (concat docbook-menu-xsl-dir "/html/profile-docbook.xsl")) t]
	      ["profile-onechunk.xsl" (find-file (concat docbook-menu-xsl-dir "/html/profile-onechunk.xsl")) t]
	      ["qandaset.xsl" (find-file (concat docbook-menu-xsl-dir "/html/qandaset.xsl")) t]
	      ["refentry.xsl" (find-file (concat docbook-menu-xsl-dir "/html/refentry.xsl")) t]
	      ["sections.xsl" (find-file (concat docbook-menu-xsl-dir "/html/sections.xsl")) t]
	      ["synop.xsl" (find-file (concat docbook-menu-xsl-dir "/html/synop.xsl")) t]
	      ["table.xsl" (find-file (concat docbook-menu-xsl-dir "/html/table.xsl")) t]
	      ["task.xsl" (find-file (concat docbook-menu-xsl-dir "/html/task.xsl")) t]
	      ["titlepage.templates.xml" (find-file (concat docbook-menu-xsl-dir "/html/titlepage.templates.xml")) t]
	      ["titlepage.templates.xsl" (find-file (concat docbook-menu-xsl-dir "/html/titlepage.templates.xsl")) t]
	      ["titlepage.xsl" (find-file (concat docbook-menu-xsl-dir "/html/titlepage.xsl")) t]
	      ["toc.xsl" (find-file (concat docbook-menu-xsl-dir "/html/toc.xsl")) t]
	      ["verbatim.xsl" (find-file (concat docbook-menu-xsl-dir "/html/verbatim.xsl")) t]
	      ["xref.xsl" (find-file (concat docbook-menu-xsl-dir "/html/xref.xsl")) t]
	      )
	(list "htmlhelp"
	      ["ChangeLog" (find-file (concat docbook-menu-xsl-dir "/htmlhelp/ChangeLog")) t]
	      ["htmlhelp-common.xsl" (find-file (concat docbook-menu-xsl-dir "/htmlhelp/htmlhelp-common.xsl")) t]
	      ["htmlhelp.xsl" (find-file (concat docbook-menu-xsl-dir "/htmlhelp/htmlhelp.xsl")) t]
	      ["profile-htmlhelp-common.xsl" (find-file (concat docbook-menu-xsl-dir "/htmlhelp/profile-htmlhelp-common.xsl")) t]
	      ["profile-htmlhelp.xsl" (find-file (concat docbook-menu-xsl-dir "/htmlhelp/profile-htmlhelp.xsl")) t]
	      )
	(list "images"
	      (list "callouts"
		    ["1.gif" (find-file (concat docbook-menu-xsl-dir "/images/callouts/1.gif")) t]
		    ["1.png" (find-file (concat docbook-menu-xsl-dir "/images/callouts/1.png")) t]
		    ["10.gif" (find-file (concat docbook-menu-xsl-dir "/images/callouts/10.gif")) t]
		    ["10.png" (find-file (concat docbook-menu-xsl-dir "/images/callouts/10.png")) t]
		    ["11.gif" (find-file (concat docbook-menu-xsl-dir "/images/callouts/11.gif")) t]
		    ["11.png" (find-file (concat docbook-menu-xsl-dir "/images/callouts/11.png")) t]
		    ["12.gif" (find-file (concat docbook-menu-xsl-dir "/images/callouts/12.gif")) t]
		    ["12.png" (find-file (concat docbook-menu-xsl-dir "/images/callouts/12.png")) t]
		    ["13.gif" (find-file (concat docbook-menu-xsl-dir "/images/callouts/13.gif")) t]
		    ["13.png" (find-file (concat docbook-menu-xsl-dir "/images/callouts/13.png")) t]
		    ["14.gif" (find-file (concat docbook-menu-xsl-dir "/images/callouts/14.gif")) t]
		    ["14.png" (find-file (concat docbook-menu-xsl-dir "/images/callouts/14.png")) t]
		    ["15.gif" (find-file (concat docbook-menu-xsl-dir "/images/callouts/15.gif")) t]
		    ["15.png" (find-file (concat docbook-menu-xsl-dir "/images/callouts/15.png")) t]
		    ["2.gif" (find-file (concat docbook-menu-xsl-dir "/images/callouts/2.gif")) t]
		    ["2.png" (find-file (concat docbook-menu-xsl-dir "/images/callouts/2.png")) t]
		    ["3.gif" (find-file (concat docbook-menu-xsl-dir "/images/callouts/3.gif")) t]
		    ["3.png" (find-file (concat docbook-menu-xsl-dir "/images/callouts/3.png")) t]
		    ["4.gif" (find-file (concat docbook-menu-xsl-dir "/images/callouts/4.gif")) t]
		    ["4.png" (find-file (concat docbook-menu-xsl-dir "/images/callouts/4.png")) t]
		    ["5.gif" (find-file (concat docbook-menu-xsl-dir "/images/callouts/5.gif")) t]
		    ["5.png" (find-file (concat docbook-menu-xsl-dir "/images/callouts/5.png")) t]
		    ["6.gif" (find-file (concat docbook-menu-xsl-dir "/images/callouts/6.gif")) t]
		    ["6.png" (find-file (concat docbook-menu-xsl-dir "/images/callouts/6.png")) t]
		    ["7.gif" (find-file (concat docbook-menu-xsl-dir "/images/callouts/7.gif")) t]
		    ["7.png" (find-file (concat docbook-menu-xsl-dir "/images/callouts/7.png")) t]
		    ["8.gif" (find-file (concat docbook-menu-xsl-dir "/images/callouts/8.gif")) t]
		    ["8.png" (find-file (concat docbook-menu-xsl-dir "/images/callouts/8.png")) t]
		    ["9.gif" (find-file (concat docbook-menu-xsl-dir "/images/callouts/9.gif")) t]
		    ["9.png" (find-file (concat docbook-menu-xsl-dir "/images/callouts/9.png")) t]
		    ["ChangeLog" (find-file (concat docbook-menu-xsl-dir "/images/callouts/ChangeLog")) t]
		    )
	      ["ChangeLog" (find-file (concat docbook-menu-xsl-dir "/images/ChangeLog")) t]
	      ["blank.png" (find-file (concat docbook-menu-xsl-dir "/images/blank.png")) t]
	      ["caution.gif" (find-file (concat docbook-menu-xsl-dir "/images/caution.gif")) t]
	      ["caution.png" (find-file (concat docbook-menu-xsl-dir "/images/caution.png")) t]
	      ["caution.tif" (find-file (concat docbook-menu-xsl-dir "/images/caution.tif")) t]
	      ["draft.png" (find-file (concat docbook-menu-xsl-dir "/images/draft.png")) t]
	      ["home.gif" (find-file (concat docbook-menu-xsl-dir "/images/home.gif")) t]
	      ["home.png" (find-file (concat docbook-menu-xsl-dir "/images/home.png")) t]
	      ["important.gif" (find-file (concat docbook-menu-xsl-dir "/images/important.gif")) t]
	      ["important.png" (find-file (concat docbook-menu-xsl-dir "/images/important.png")) t]
	      ["important.tif" (find-file (concat docbook-menu-xsl-dir "/images/important.tif")) t]
	      ["next.gif" (find-file (concat docbook-menu-xsl-dir "/images/next.gif")) t]
	      ["next.png" (find-file (concat docbook-menu-xsl-dir "/images/next.png")) t]
	      ["note.gif" (find-file (concat docbook-menu-xsl-dir "/images/note.gif")) t]
	      ["note.png" (find-file (concat docbook-menu-xsl-dir "/images/note.png")) t]
	      ["note.tif" (find-file (concat docbook-menu-xsl-dir "/images/note.tif")) t]
	      ["prev.gif" (find-file (concat docbook-menu-xsl-dir "/images/prev.gif")) t]
	      ["prev.png" (find-file (concat docbook-menu-xsl-dir "/images/prev.png")) t]
	      ["tip.gif" (find-file (concat docbook-menu-xsl-dir "/images/tip.gif")) t]
	      ["tip.png" (find-file (concat docbook-menu-xsl-dir "/images/tip.png")) t]
	      ["tip.tif" (find-file (concat docbook-menu-xsl-dir "/images/tip.tif")) t]
	      ["toc-blank.png" (find-file (concat docbook-menu-xsl-dir "/images/toc-blank.png")) t]
	      ["toc-minus.png" (find-file (concat docbook-menu-xsl-dir "/images/toc-minus.png")) t]
	      ["toc-plus.png" (find-file (concat docbook-menu-xsl-dir "/images/toc-plus.png")) t]
	      ["up.gif" (find-file (concat docbook-menu-xsl-dir "/images/up.gif")) t]
	      ["up.png" (find-file (concat docbook-menu-xsl-dir "/images/up.png")) t]
	      ["warning.gif" (find-file (concat docbook-menu-xsl-dir "/images/warning.gif")) t]
	      ["warning.png" (find-file (concat docbook-menu-xsl-dir "/images/warning.png")) t]
	      ["warning.tif" (find-file (concat docbook-menu-xsl-dir "/images/warning.tif")) t]
	      )
	(list "javahelp"
	      ["ChangeLog" (find-file (concat docbook-menu-xsl-dir "/javahelp/ChangeLog")) t]
	      ["javahelp.xsl" (find-file (concat docbook-menu-xsl-dir "/javahelp/javahelp.xsl")) t]
	      ["profile-javahelp.xsl" (find-file (concat docbook-menu-xsl-dir "/javahelp/profile-javahelp.xsl")) t]
	      )
	(list "lib"
	      ["ChangeLog" (find-file (concat docbook-menu-xsl-dir "/lib/ChangeLog")) t]
	      ["lib.xml" (find-file (concat docbook-menu-xsl-dir "/lib/lib.xml")) t]
	      ["lib.xsl" (find-file (concat docbook-menu-xsl-dir "/lib/lib.xsl")) t]
	      ["lib.xweb" (find-file (concat docbook-menu-xsl-dir "/lib/lib.xweb")) t]
	      )
	(list "manpages"
	      ["ChangeLog" (find-file (concat docbook-menu-xsl-dir "/manpages/ChangeLog")) t]
	      ["README" (find-file (concat docbook-menu-xsl-dir "/manpages/README")) t]
	      ["docbook.xsl" (find-file (concat docbook-menu-xsl-dir "/manpages/docbook.xsl")) t]
	      ["lists.xsl" (find-file (concat docbook-menu-xsl-dir "/manpages/lists.xsl")) t]
	      ["sect23.xsl" (find-file (concat docbook-menu-xsl-dir "/manpages/sect23.xsl")) t]
	      ["synop.xsl" (find-file (concat docbook-menu-xsl-dir "/manpages/synop.xsl")) t]
	      ["xref.xsl" (find-file (concat docbook-menu-xsl-dir "/manpages/xref.xsl")) t]
	      )
	(list "params"
	      ["ChangeLog" (find-file (concat docbook-menu-xsl-dir "/params/ChangeLog")) t]
	      ["admon.graphics.extension.xml" (find-file (concat docbook-menu-xsl-dir "/params/admon.graphics.extension.xml")) t]
	      ["admon.graphics.path.xml" (find-file (concat docbook-menu-xsl-dir "/params/admon.graphics.path.xml")) t]
	      ["admon.graphics.xml" (find-file (concat docbook-menu-xsl-dir "/params/admon.graphics.xml")) t]
	      ["admon.style.xml" (find-file (concat docbook-menu-xsl-dir "/params/admon.style.xml")) t]
	      ["admon.textlabel.xml" (find-file (concat docbook-menu-xsl-dir "/params/admon.textlabel.xml")) t]
	      ["admonition.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/admonition.properties.xml")) t]
	      ["admonition.title.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/admonition.title.properties.xml")) t]
	      ["alignment.xml" (find-file (concat docbook-menu-xsl-dir "/params/alignment.xml")) t]
	      ["annotate.toc.xml" (find-file (concat docbook-menu-xsl-dir "/params/annotate.toc.xml")) t]
	      ["appendix.autolabel.xml" (find-file (concat docbook-menu-xsl-dir "/params/appendix.autolabel.xml")) t]
	      ["arbortext.extensions.xml" (find-file (concat docbook-menu-xsl-dir "/params/arbortext.extensions.xml")) t]
	      ["author.othername.in.middle.xml" (find-file (concat docbook-menu-xsl-dir "/params/author.othername.in.middle.xml")) t]
	      ["autotoc.label.separator.xml" (find-file (concat docbook-menu-xsl-dir "/params/autotoc.label.separator.xml")) t]
	      ["axf.extensions.xml" (find-file (concat docbook-menu-xsl-dir "/params/axf.extensions.xml")) t]
	      ["base.dir.xml" (find-file (concat docbook-menu-xsl-dir "/params/base.dir.xml")) t]
	      ["biblioentry.item.separator.xml" (find-file (concat docbook-menu-xsl-dir "/params/biblioentry.item.separator.xml")) t]
	      ["bibliography.collection.xml" (find-file (concat docbook-menu-xsl-dir "/params/bibliography.collection.xml")) t]
	      ["bibliography.numbered.xml" (find-file (concat docbook-menu-xsl-dir "/params/bibliography.numbered.xml")) t]
	      ["blockquote.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/blockquote.properties.xml")) t]
	      ["body.font.family.xml" (find-file (concat docbook-menu-xsl-dir "/params/body.font.family.xml")) t]
	      ["body.font.master.xml" (find-file (concat docbook-menu-xsl-dir "/params/body.font.master.xml")) t]
	      ["body.font.size.xml" (find-file (concat docbook-menu-xsl-dir "/params/body.font.size.xml")) t]
	      ["body.margin.bottom.xml" (find-file (concat docbook-menu-xsl-dir "/params/body.margin.bottom.xml")) t]
	      ["body.margin.top.xml" (find-file (concat docbook-menu-xsl-dir "/params/body.margin.top.xml")) t]
	      ["bridgehead.in.toc.xml" (find-file (concat docbook-menu-xsl-dir "/params/bridgehead.in.toc.xml")) t]
	      ["callout.defaultcolumn.xml" (find-file (concat docbook-menu-xsl-dir "/params/callout.defaultcolumn.xml")) t]
	      ["callout.graphics.extension.xml" (find-file (concat docbook-menu-xsl-dir "/params/callout.graphics.extension.xml")) t]
	      ["callout.graphics.number.limit.xml" (find-file (concat docbook-menu-xsl-dir "/params/callout.graphics.number.limit.xml")) t]
	      ["callout.graphics.path.xml" (find-file (concat docbook-menu-xsl-dir "/params/callout.graphics.path.xml")) t]
	      ["callout.graphics.xml" (find-file (concat docbook-menu-xsl-dir "/params/callout.graphics.xml")) t]
	      ["callout.list.table.xml" (find-file (concat docbook-menu-xsl-dir "/params/callout.list.table.xml")) t]
	      ["callout.unicode.font.xml" (find-file (concat docbook-menu-xsl-dir "/params/callout.unicode.font.xml")) t]
	      ["callout.unicode.number.limit.xml" (find-file (concat docbook-menu-xsl-dir "/params/callout.unicode.number.limit.xml")) t]
	      ["callout.unicode.start.character.xml" (find-file (concat docbook-menu-xsl-dir "/params/callout.unicode.start.character.xml")) t]
	      ["callout.unicode.xml" (find-file (concat docbook-menu-xsl-dir "/params/callout.unicode.xml")) t]
	      ["callouts.extension.xml" (find-file (concat docbook-menu-xsl-dir "/params/callouts.extension.xml")) t]
	      ["chapter.autolabel.xml" (find-file (concat docbook-menu-xsl-dir "/params/chapter.autolabel.xml")) t]
	      ["chunk.first.sections.xml" (find-file (concat docbook-menu-xsl-dir "/params/chunk.first.sections.xml")) t]
	      ["chunk.quietly.xml" (find-file (concat docbook-menu-xsl-dir "/params/chunk.quietly.xml")) t]
	      ["chunk.section.depth.xml" (find-file (concat docbook-menu-xsl-dir "/params/chunk.section.depth.xml")) t]
	      ["chunk.sections.xml" (find-file (concat docbook-menu-xsl-dir "/params/chunk.sections.xml")) t]
	      ["chunk.toc.xml" (find-file (concat docbook-menu-xsl-dir "/params/chunk.toc.xml")) t]
	      ["chunk.tocs.and.lots.xml" (find-file (concat docbook-menu-xsl-dir "/params/chunk.tocs.and.lots.xml")) t]
	      ["chunker.output.cdata-section-elements.xml" (find-file (concat docbook-menu-xsl-dir "/params/chunker.output.cdata-section-elements.xml")) t]
	      ["chunker.output.doctype-public.xml" (find-file (concat docbook-menu-xsl-dir "/params/chunker.output.doctype-public.xml")) t]
	      ["chunker.output.doctype-system.xml" (find-file (concat docbook-menu-xsl-dir "/params/chunker.output.doctype-system.xml")) t]
	      ["chunker.output.encoding.xml" (find-file (concat docbook-menu-xsl-dir "/params/chunker.output.encoding.xml")) t]
	      ["chunker.output.indent.xml" (find-file (concat docbook-menu-xsl-dir "/params/chunker.output.indent.xml")) t]
	      ["chunker.output.media-type.xml" (find-file (concat docbook-menu-xsl-dir "/params/chunker.output.media-type.xml")) t]
	      ["chunker.output.method.xml" (find-file (concat docbook-menu-xsl-dir "/params/chunker.output.method.xml")) t]
	      ["chunker.output.omit-xml-declaration.xml" (find-file (concat docbook-menu-xsl-dir "/params/chunker.output.omit-xml-declaration.xml")) t]
	      ["chunker.output.standalone.xml" (find-file (concat docbook-menu-xsl-dir "/params/chunker.output.standalone.xml")) t]
	      ["citerefentry.link.xml" (find-file (concat docbook-menu-xsl-dir "/params/citerefentry.link.xml")) t]
	      ["collect.xref.targets.xml" (find-file (concat docbook-menu-xsl-dir "/params/collect.xref.targets.xml")) t]
	      ["column.count.back.xml" (find-file (concat docbook-menu-xsl-dir "/params/column.count.back.xml")) t]
	      ["column.count.body.xml" (find-file (concat docbook-menu-xsl-dir "/params/column.count.body.xml")) t]
	      ["column.count.front.xml" (find-file (concat docbook-menu-xsl-dir "/params/column.count.front.xml")) t]
	      ["column.count.index.xml" (find-file (concat docbook-menu-xsl-dir "/params/column.count.index.xml")) t]
	      ["column.count.lot.xml" (find-file (concat docbook-menu-xsl-dir "/params/column.count.lot.xml")) t]
	      ["column.count.titlepage.xml" (find-file (concat docbook-menu-xsl-dir "/params/column.count.titlepage.xml")) t]
	      ["column.gap.back.xml" (find-file (concat docbook-menu-xsl-dir "/params/column.gap.back.xml")) t]
	      ["column.gap.body.xml" (find-file (concat docbook-menu-xsl-dir "/params/column.gap.body.xml")) t]
	      ["column.gap.front.xml" (find-file (concat docbook-menu-xsl-dir "/params/column.gap.front.xml")) t]
	      ["column.gap.index.xml" (find-file (concat docbook-menu-xsl-dir "/params/column.gap.index.xml")) t]
	      ["column.gap.lot.xml" (find-file (concat docbook-menu-xsl-dir "/params/column.gap.lot.xml")) t]
	      ["column.gap.titlepage.xml" (find-file (concat docbook-menu-xsl-dir "/params/column.gap.titlepage.xml")) t]
	      ["compact.list.item.spacing.xml" (find-file (concat docbook-menu-xsl-dir "/params/compact.list.item.spacing.xml")) t]
	      ["css.decoration.xml" (find-file (concat docbook-menu-xsl-dir "/params/css.decoration.xml")) t]
	      ["current.docid.xml" (find-file (concat docbook-menu-xsl-dir "/params/current.docid.xml")) t]
	      ["default.float.class.xml" (find-file (concat docbook-menu-xsl-dir "/params/default.float.class.xml")) t]
	      ["default.image.width.xml" (find-file (concat docbook-menu-xsl-dir "/params/default.image.width.xml")) t]
	      ["default.table.width.xml" (find-file (concat docbook-menu-xsl-dir "/params/default.table.width.xml")) t]
	      ["default.units.xml" (find-file (concat docbook-menu-xsl-dir "/params/default.units.xml")) t]
	      ["dingbat.font.family.xml" (find-file (concat docbook-menu-xsl-dir "/params/dingbat.font.family.xml")) t]
	      ["double.sided.xml" (find-file (concat docbook-menu-xsl-dir "/params/double.sided.xml")) t]
	      ["draft.mode.xml" (find-file (concat docbook-menu-xsl-dir "/params/draft.mode.xml")) t]
	      ["draft.watermark.image.xml" (find-file (concat docbook-menu-xsl-dir "/params/draft.watermark.image.xml")) t]
	      ["ebnf.assignment.xml" (find-file (concat docbook-menu-xsl-dir "/params/ebnf.assignment.xml")) t]
	      ["ebnf.statement.terminator.xml" (find-file (concat docbook-menu-xsl-dir "/params/ebnf.statement.terminator.xml")) t]
	      ["ebnf.table.bgcolor.xml" (find-file (concat docbook-menu-xsl-dir "/params/ebnf.table.bgcolor.xml")) t]
	      ["ebnf.table.border.xml" (find-file (concat docbook-menu-xsl-dir "/params/ebnf.table.border.xml")) t]
	      ["eclipse.autolabel.xml" (find-file (concat docbook-menu-xsl-dir "/params/eclipse.autolabel.xml")) t]
	      ["eclipse.plugin.id.xml" (find-file (concat docbook-menu-xsl-dir "/params/eclipse.plugin.id.xml")) t]
	      ["eclipse.plugin.name.xml" (find-file (concat docbook-menu-xsl-dir "/params/eclipse.plugin.name.xml")) t]
	      ["eclipse.plugin.provider.xml" (find-file (concat docbook-menu-xsl-dir "/params/eclipse.plugin.provider.xml")) t]
	      ["emphasis.propagates.style.xml" (find-file (concat docbook-menu-xsl-dir "/params/emphasis.propagates.style.xml")) t]
	      ["entry.propagates.style.xml" (find-file (concat docbook-menu-xsl-dir "/params/entry.propagates.style.xml")) t]
	      ["equation.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/equation.properties.xml")) t]
	      ["example.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/example.properties.xml")) t]
	      ["figure.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/figure.properties.xml")) t]
	      ["firstterm.only.link.xml" (find-file (concat docbook-menu-xsl-dir "/params/firstterm.only.link.xml")) t]
	      ["footer.content.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/footer.content.properties.xml")) t]
	      ["footer.rule.xml" (find-file (concat docbook-menu-xsl-dir "/params/footer.rule.xml")) t]
	      ["footers.on.blank.pages.xml" (find-file (concat docbook-menu-xsl-dir "/params/footers.on.blank.pages.xml")) t]
	      ["footnote.font.size.xml" (find-file (concat docbook-menu-xsl-dir "/params/footnote.font.size.xml")) t]
	      ["footnote.number.format.xml" (find-file (concat docbook-menu-xsl-dir "/params/footnote.number.format.xml")) t]
	      ["footnote.number.symbols.xml" (find-file (concat docbook-menu-xsl-dir "/params/footnote.number.symbols.xml")) t]
	      ["fop.extensions.xml" (find-file (concat docbook-menu-xsl-dir "/params/fop.extensions.xml")) t]
	      ["formal.object.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/formal.object.properties.xml")) t]
	      ["formal.procedures.xml" (find-file (concat docbook-menu-xsl-dir "/params/formal.procedures.xml")) t]
	      ["formal.title.placement.xml" (find-file (concat docbook-menu-xsl-dir "/params/formal.title.placement.xml")) t]
	      ["formal.title.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/formal.title.properties.xml")) t]
	      ["funcsynopsis.decoration.xml" (find-file (concat docbook-menu-xsl-dir "/params/funcsynopsis.decoration.xml")) t]
	      ["funcsynopsis.style.xml" (find-file (concat docbook-menu-xsl-dir "/params/funcsynopsis.style.xml")) t]
	      ["funcsynopsis.tabular.threshold.xml" (find-file (concat docbook-menu-xsl-dir "/params/funcsynopsis.tabular.threshold.xml")) t]
	      ["function.parens.xml" (find-file (concat docbook-menu-xsl-dir "/params/function.parens.xml")) t]
	      ["generate.id.attributes.xml" (find-file (concat docbook-menu-xsl-dir "/params/generate.id.attributes.xml")) t]
	      ["generate.index.xml" (find-file (concat docbook-menu-xsl-dir "/params/generate.index.xml")) t]
	      ["generate.legalnotice.link.xml" (find-file (concat docbook-menu-xsl-dir "/params/generate.legalnotice.link.xml")) t]
	      ["generate.manifest.xml" (find-file (concat docbook-menu-xsl-dir "/params/generate.manifest.xml")) t]
	      ["generate.meta.abstract.xml" (find-file (concat docbook-menu-xsl-dir "/params/generate.meta.abstract.xml")) t]
	      ["generate.section.toc.level.xml" (find-file (concat docbook-menu-xsl-dir "/params/generate.section.toc.level.xml")) t]
	      ["generate.toc.xml" (find-file (concat docbook-menu-xsl-dir "/params/generate.toc.xml")) t]
	      ["glossary.as.blocks.xml" (find-file (concat docbook-menu-xsl-dir "/params/glossary.as.blocks.xml")) t]
	      ["glossary.collection.xml" (find-file (concat docbook-menu-xsl-dir "/params/glossary.collection.xml")) t]
	      ["glossentry.show.acronym.xml" (find-file (concat docbook-menu-xsl-dir "/params/glossentry.show.acronym.xml")) t]
	      ["glosslist.as.blocks.xml" (find-file (concat docbook-menu-xsl-dir "/params/glosslist.as.blocks.xml")) t]
	      ["glossterm.auto.link.xml" (find-file (concat docbook-menu-xsl-dir "/params/glossterm.auto.link.xml")) t]
	      ["glossterm.separation.xml" (find-file (concat docbook-menu-xsl-dir "/params/glossterm.separation.xml")) t]
	      ["glossterm.width.xml" (find-file (concat docbook-menu-xsl-dir "/params/glossterm.width.xml")) t]
	      ["graphic.default.extension.xml" (find-file (concat docbook-menu-xsl-dir "/params/graphic.default.extension.xml")) t]
	      ["graphicsize.extension.xml" (find-file (concat docbook-menu-xsl-dir "/params/graphicsize.extension.xml")) t]
	      ["header.content.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/header.content.properties.xml")) t]
	      ["header.rule.xml" (find-file (concat docbook-menu-xsl-dir "/params/header.rule.xml")) t]
	      ["headers.on.blank.pages.xml" (find-file (concat docbook-menu-xsl-dir "/params/headers.on.blank.pages.xml")) t]
	      ["html.base.xml" (find-file (concat docbook-menu-xsl-dir "/params/html.base.xml")) t]
	      ["html.cellpadding.xml" (find-file (concat docbook-menu-xsl-dir "/params/html.cellpadding.xml")) t]
	      ["html.cellspacing.xml" (find-file (concat docbook-menu-xsl-dir "/params/html.cellspacing.xml")) t]
	      ["html.cleanup.xml" (find-file (concat docbook-menu-xsl-dir "/params/html.cleanup.xml")) t]
	      ["html.ext.xml" (find-file (concat docbook-menu-xsl-dir "/params/html.ext.xml")) t]
	      ["html.extra.head.links.xml" (find-file (concat docbook-menu-xsl-dir "/params/html.extra.head.links.xml")) t]
	      ["html.longdesc.link.xml" (find-file (concat docbook-menu-xsl-dir "/params/html.longdesc.link.xml")) t]
	      ["html.longdesc.xml" (find-file (concat docbook-menu-xsl-dir "/params/html.longdesc.xml")) t]
	      ["html.stylesheet.type.xml" (find-file (concat docbook-menu-xsl-dir "/params/html.stylesheet.type.xml")) t]
	      ["html.stylesheet.xml" (find-file (concat docbook-menu-xsl-dir "/params/html.stylesheet.xml")) t]
	      ["htmlhelp.alias.file.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.alias.file.xml")) t]
	      ["htmlhelp.autolabel.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.autolabel.xml")) t]
	      ["htmlhelp.button.back.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.button.back.xml")) t]
	      ["htmlhelp.button.forward.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.button.forward.xml")) t]
	      ["htmlhelp.button.hideshow.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.button.hideshow.xml")) t]
	      ["htmlhelp.button.home.url.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.button.home.url.xml")) t]
	      ["htmlhelp.button.home.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.button.home.xml")) t]
	      ["htmlhelp.button.jump1.title.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.button.jump1.title.xml")) t]
	      ["htmlhelp.button.jump1.url.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.button.jump1.url.xml")) t]
	      ["htmlhelp.button.jump1.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.button.jump1.xml")) t]
	      ["htmlhelp.button.jump2.title.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.button.jump2.title.xml")) t]
	      ["htmlhelp.button.jump2.url.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.button.jump2.url.xml")) t]
	      ["htmlhelp.button.jump2.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.button.jump2.xml")) t]
	      ["htmlhelp.button.locate.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.button.locate.xml")) t]
	      ["htmlhelp.button.next.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.button.next.xml")) t]
	      ["htmlhelp.button.options.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.button.options.xml")) t]
	      ["htmlhelp.button.prev.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.button.prev.xml")) t]
	      ["htmlhelp.button.print.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.button.print.xml")) t]
	      ["htmlhelp.button.refresh.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.button.refresh.xml")) t]
	      ["htmlhelp.button.stop.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.button.stop.xml")) t]
	      ["htmlhelp.button.zoom.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.button.zoom.xml")) t]
	      ["htmlhelp.chm.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.chm.xml")) t]
	      ["htmlhelp.default.topic.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.default.topic.xml")) t]
	      ["htmlhelp.encoding.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.encoding.xml")) t]
	      ["htmlhelp.enumerate.images.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.enumerate.images.xml")) t]
	      ["htmlhelp.force.map.and.alias.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.force.map.and.alias.xml")) t]
	      ["htmlhelp.hhc.binary.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.hhc.binary.xml")) t]
	      ["htmlhelp.hhc.folders.instead.books.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.hhc.folders.instead.books.xml")) t]
	      ["htmlhelp.hhc.section.depth.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.hhc.section.depth.xml")) t]
	      ["htmlhelp.hhc.show.root.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.hhc.show.root.xml")) t]
	      ["htmlhelp.hhc.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.hhc.xml")) t]
	      ["htmlhelp.hhk.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.hhk.xml")) t]
	      ["htmlhelp.hhp.tail.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.hhp.tail.xml")) t]
	      ["htmlhelp.hhp.window.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.hhp.window.xml")) t]
	      ["htmlhelp.hhp.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.hhp.xml")) t]
	      ["htmlhelp.map.file.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.map.file.xml")) t]
	      ["htmlhelp.only.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.only.xml")) t]
	      ["htmlhelp.show.advanced.search.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.show.advanced.search.xml")) t]
	      ["htmlhelp.show.favorities.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.show.favorities.xml")) t]
	      ["htmlhelp.show.menu.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.show.menu.xml")) t]
	      ["htmlhelp.title.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.title.xml")) t]
	      ["htmlhelp.use.hhk.xml" (find-file (concat docbook-menu-xsl-dir "/params/htmlhelp.use.hhk.xml")) t]
	      ["hyphenate.xml" (find-file (concat docbook-menu-xsl-dir "/params/hyphenate.xml")) t]
	      ["ignore.image.scaling.xml" (find-file (concat docbook-menu-xsl-dir "/params/ignore.image.scaling.xml")) t]
	      ["informal.object.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/informal.object.properties.xml")) t]
	      ["inherit.keywords.xml" (find-file (concat docbook-menu-xsl-dir "/params/inherit.keywords.xml")) t]
	      ["insert.xref.page.number.xml" (find-file (concat docbook-menu-xsl-dir "/params/insert.xref.page.number.xml")) t]
	      ["l10n.gentext.default.language.xml" (find-file (concat docbook-menu-xsl-dir "/params/l10n.gentext.default.language.xml")) t]
	      ["l10n.gentext.language.xml" (find-file (concat docbook-menu-xsl-dir "/params/l10n.gentext.language.xml")) t]
	      ["l10n.gentext.use.xref.language.xml" (find-file (concat docbook-menu-xsl-dir "/params/l10n.gentext.use.xref.language.xml")) t]
	      ["label.from.part.xml" (find-file (concat docbook-menu-xsl-dir "/params/label.from.part.xml")) t]
	      ["line-height.xml" (find-file (concat docbook-menu-xsl-dir "/params/line-height.xml")) t]
	      ["linenumbering.everyNth.xml" (find-file (concat docbook-menu-xsl-dir "/params/linenumbering.everyNth.xml")) t]
	      ["linenumbering.extension.xml" (find-file (concat docbook-menu-xsl-dir "/params/linenumbering.extension.xml")) t]
	      ["linenumbering.separator.xml" (find-file (concat docbook-menu-xsl-dir "/params/linenumbering.separator.xml")) t]
	      ["linenumbering.width.xml" (find-file (concat docbook-menu-xsl-dir "/params/linenumbering.width.xml")) t]
	      ["link.mailto.url.xml" (find-file (concat docbook-menu-xsl-dir "/params/link.mailto.url.xml")) t]
	      ["list.block.spacing.xml" (find-file (concat docbook-menu-xsl-dir "/params/list.block.spacing.xml")) t]
	      ["list.item.spacing.xml" (find-file (concat docbook-menu-xsl-dir "/params/list.item.spacing.xml")) t]
	      ["make.graphic.viewport.xml" (find-file (concat docbook-menu-xsl-dir "/params/make.graphic.viewport.xml")) t]
	      ["make.index.markup.xml" (find-file (concat docbook-menu-xsl-dir "/params/make.index.markup.xml")) t]
	      ["make.single.year.ranges.xml" (find-file (concat docbook-menu-xsl-dir "/params/make.single.year.ranges.xml")) t]
	      ["make.valid.html.xml" (find-file (concat docbook-menu-xsl-dir "/params/make.valid.html.xml")) t]
	      ["make.year.ranges.xml" (find-file (concat docbook-menu-xsl-dir "/params/make.year.ranges.xml")) t]
	      ["manifest.in.base.dir.xml" (find-file (concat docbook-menu-xsl-dir "/params/manifest.in.base.dir.xml")) t]
	      ["manifest.xml" (find-file (concat docbook-menu-xsl-dir "/params/manifest.xml")) t]
	      ["manual.toc.xml" (find-file (concat docbook-menu-xsl-dir "/params/manual.toc.xml")) t]
	      ["menuchoice.menu.separator.xml" (find-file (concat docbook-menu-xsl-dir "/params/menuchoice.menu.separator.xml")) t]
	      ["menuchoice.separator.xml" (find-file (concat docbook-menu-xsl-dir "/params/menuchoice.separator.xml")) t]
	      ["monospace.font.family.xml" (find-file (concat docbook-menu-xsl-dir "/params/monospace.font.family.xml")) t]
	      ["monospace.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/monospace.properties.xml")) t]
	      ["monospace.verbatim.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/monospace.verbatim.properties.xml")) t]
	      ["navig.graphics.extension.xml" (find-file (concat docbook-menu-xsl-dir "/params/navig.graphics.extension.xml")) t]
	      ["navig.graphics.path.xml" (find-file (concat docbook-menu-xsl-dir "/params/navig.graphics.path.xml")) t]
	      ["navig.graphics.xml" (find-file (concat docbook-menu-xsl-dir "/params/navig.graphics.xml")) t]
	      ["navig.showtitles.xml" (find-file (concat docbook-menu-xsl-dir "/params/navig.showtitles.xml")) t]
	      ["nominal.image.depth.xml" (find-file (concat docbook-menu-xsl-dir "/params/nominal.image.depth.xml")) t]
	      ["nominal.image.width.xml" (find-file (concat docbook-menu-xsl-dir "/params/nominal.image.width.xml")) t]
	      ["nominal.table.width.xml" (find-file (concat docbook-menu-xsl-dir "/params/nominal.table.width.xml")) t]
	      ["normal.para.spacing.xml" (find-file (concat docbook-menu-xsl-dir "/params/normal.para.spacing.xml")) t]
	      ["olink.base.uri.xml" (find-file (concat docbook-menu-xsl-dir "/params/olink.base.uri.xml")) t]
	      ["olink.doctitle.xml" (find-file (concat docbook-menu-xsl-dir "/params/olink.doctitle.xml")) t]
	      ["olink.fragid.xml" (find-file (concat docbook-menu-xsl-dir "/params/olink.fragid.xml")) t]
	      ["olink.outline.ext.xml" (find-file (concat docbook-menu-xsl-dir "/params/olink.outline.ext.xml")) t]
	      ["olink.pubid.xml" (find-file (concat docbook-menu-xsl-dir "/params/olink.pubid.xml")) t]
	      ["olink.resolver.xml" (find-file (concat docbook-menu-xsl-dir "/params/olink.resolver.xml")) t]
	      ["olink.sysid.xml" (find-file (concat docbook-menu-xsl-dir "/params/olink.sysid.xml")) t]
	      ["page.height.portrait.xml" (find-file (concat docbook-menu-xsl-dir "/params/page.height.portrait.xml")) t]
	      ["page.height.xml" (find-file (concat docbook-menu-xsl-dir "/params/page.height.xml")) t]
	      ["page.margin.bottom.xml" (find-file (concat docbook-menu-xsl-dir "/params/page.margin.bottom.xml")) t]
	      ["page.margin.inner.xml" (find-file (concat docbook-menu-xsl-dir "/params/page.margin.inner.xml")) t]
	      ["page.margin.outer.xml" (find-file (concat docbook-menu-xsl-dir "/params/page.margin.outer.xml")) t]
	      ["page.margin.top.xml" (find-file (concat docbook-menu-xsl-dir "/params/page.margin.top.xml")) t]
	      ["page.orientation.xml" (find-file (concat docbook-menu-xsl-dir "/params/page.orientation.xml")) t]
	      ["page.width.portrait.xml" (find-file (concat docbook-menu-xsl-dir "/params/page.width.portrait.xml")) t]
	      ["page.width.xml" (find-file (concat docbook-menu-xsl-dir "/params/page.width.xml")) t]
	      ["paper.type.xml" (find-file (concat docbook-menu-xsl-dir "/params/paper.type.xml")) t]
	      ["para.propagates.style.xml" (find-file (concat docbook-menu-xsl-dir "/params/para.propagates.style.xml")) t]
	      ["part.autolabel.xml" (find-file (concat docbook-menu-xsl-dir "/params/part.autolabel.xml")) t]
	      ["passivetex.extensions.xml" (find-file (concat docbook-menu-xsl-dir "/params/passivetex.extensions.xml")) t]
	      ["phrase.propagates.style.xml" (find-file (concat docbook-menu-xsl-dir "/params/phrase.propagates.style.xml")) t]
	      ["pixels.per.inch.xml" (find-file (concat docbook-menu-xsl-dir "/params/pixels.per.inch.xml")) t]
	      ["points.per.em.xml" (find-file (concat docbook-menu-xsl-dir "/params/points.per.em.xml")) t]
	      ["preface.autolabel.xml" (find-file (concat docbook-menu-xsl-dir "/params/preface.autolabel.xml")) t]
	      ["preferred.mediaobject.role.xml" (find-file (concat docbook-menu-xsl-dir "/params/preferred.mediaobject.role.xml")) t]
	      ["procedure.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/procedure.properties.xml")) t]
	      ["process.empty.source.toc.xml" (find-file (concat docbook-menu-xsl-dir "/params/process.empty.source.toc.xml")) t]
	      ["process.source.toc.xml" (find-file (concat docbook-menu-xsl-dir "/params/process.source.toc.xml")) t]
	      ["profile.arch.xml" (find-file (concat docbook-menu-xsl-dir "/params/profile.arch.xml")) t]
	      ["profile.attribute.xml" (find-file (concat docbook-menu-xsl-dir "/params/profile.attribute.xml")) t]
	      ["profile.condition.xml" (find-file (concat docbook-menu-xsl-dir "/params/profile.condition.xml")) t]
	      ["profile.conformance.xml" (find-file (concat docbook-menu-xsl-dir "/params/profile.conformance.xml")) t]
	      ["profile.lang.xml" (find-file (concat docbook-menu-xsl-dir "/params/profile.lang.xml")) t]
	      ["profile.os.xml" (find-file (concat docbook-menu-xsl-dir "/params/profile.os.xml")) t]
	      ["profile.revision.xml" (find-file (concat docbook-menu-xsl-dir "/params/profile.revision.xml")) t]
	      ["profile.revisionflag.xml" (find-file (concat docbook-menu-xsl-dir "/params/profile.revisionflag.xml")) t]
	      ["profile.role.xml" (find-file (concat docbook-menu-xsl-dir "/params/profile.role.xml")) t]
	      ["profile.security.xml" (find-file (concat docbook-menu-xsl-dir "/params/profile.security.xml")) t]
	      ["profile.separator.xml" (find-file (concat docbook-menu-xsl-dir "/params/profile.separator.xml")) t]
	      ["profile.userlevel.xml" (find-file (concat docbook-menu-xsl-dir "/params/profile.userlevel.xml")) t]
	      ["profile.value.xml" (find-file (concat docbook-menu-xsl-dir "/params/profile.value.xml")) t]
	      ["profile.vendor.xml" (find-file (concat docbook-menu-xsl-dir "/params/profile.vendor.xml")) t]
	      ["punct.honorific.xml" (find-file (concat docbook-menu-xsl-dir "/params/punct.honorific.xml")) t]
	      ["qanda.defaultlabel.xml" (find-file (concat docbook-menu-xsl-dir "/params/qanda.defaultlabel.xml")) t]
	      ["qanda.inherit.numeration.xml" (find-file (concat docbook-menu-xsl-dir "/params/qanda.inherit.numeration.xml")) t]
	      ["qanda.title.level1.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/qanda.title.level1.properties.xml")) t]
	      ["qanda.title.level2.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/qanda.title.level2.properties.xml")) t]
	      ["qanda.title.level3.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/qanda.title.level3.properties.xml")) t]
	      ["qanda.title.level4.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/qanda.title.level4.properties.xml")) t]
	      ["qanda.title.level5.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/qanda.title.level5.properties.xml")) t]
	      ["qanda.title.level6.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/qanda.title.level6.properties.xml")) t]
	      ["qanda.title.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/qanda.title.properties.xml")) t]
	      ["qandadiv.autolabel.xml" (find-file (concat docbook-menu-xsl-dir "/params/qandadiv.autolabel.xml")) t]
	      ["refentry.generate.name.xml" (find-file (concat docbook-menu-xsl-dir "/params/refentry.generate.name.xml")) t]
	      ["refentry.generate.title.xml" (find-file (concat docbook-menu-xsl-dir "/params/refentry.generate.title.xml")) t]
	      ["refentry.separator.xml" (find-file (concat docbook-menu-xsl-dir "/params/refentry.separator.xml")) t]
	      ["refentry.title.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/refentry.title.properties.xml")) t]
	      ["refentry.xref.manvolnum.xml" (find-file (concat docbook-menu-xsl-dir "/params/refentry.xref.manvolnum.xml")) t]
	      ["region.after.extent.xml" (find-file (concat docbook-menu-xsl-dir "/params/region.after.extent.xml")) t]
	      ["region.before.extent.xml" (find-file (concat docbook-menu-xsl-dir "/params/region.before.extent.xml")) t]
	      ["root.filename.xml" (find-file (concat docbook-menu-xsl-dir "/params/root.filename.xml")) t]
	      ["root.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/root.properties.xml")) t]
	      ["rootid.xml" (find-file (concat docbook-menu-xsl-dir "/params/rootid.xml")) t]
	      ["runinhead.default.title.end.punct.xml" (find-file (concat docbook-menu-xsl-dir "/params/runinhead.default.title.end.punct.xml")) t]
	      ["runinhead.title.end.punct.xml" (find-file (concat docbook-menu-xsl-dir "/params/runinhead.title.end.punct.xml")) t]
	      ["sans.font.family.xml" (find-file (concat docbook-menu-xsl-dir "/params/sans.font.family.xml")) t]
	      ["saxon.callouts.xml" (find-file (concat docbook-menu-xsl-dir "/params/saxon.callouts.xml")) t]
	      ["saxon.character.representation.xml" (find-file (concat docbook-menu-xsl-dir "/params/saxon.character.representation.xml")) t]
	      ["saxon.linenumbering.xml" (find-file (concat docbook-menu-xsl-dir "/params/saxon.linenumbering.xml")) t]
	      ["saxon.tablecolumns.xml" (find-file (concat docbook-menu-xsl-dir "/params/saxon.tablecolumns.xml")) t]
	      ["section.autolabel.xml" (find-file (concat docbook-menu-xsl-dir "/params/section.autolabel.xml")) t]
	      ["section.label.includes.component.label.xml" (find-file (concat docbook-menu-xsl-dir "/params/section.label.includes.component.label.xml")) t]
	      ["section.level1.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/section.level1.properties.xml")) t]
	      ["section.level2.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/section.level2.properties.xml")) t]
	      ["section.level3.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/section.level3.properties.xml")) t]
	      ["section.level4.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/section.level4.properties.xml")) t]
	      ["section.level5.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/section.level5.properties.xml")) t]
	      ["section.level6.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/section.level6.properties.xml")) t]
	      ["section.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/section.properties.xml")) t]
	      ["section.title.level1.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/section.title.level1.properties.xml")) t]
	      ["section.title.level2.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/section.title.level2.properties.xml")) t]
	      ["section.title.level3.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/section.title.level3.properties.xml")) t]
	      ["section.title.level4.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/section.title.level4.properties.xml")) t]
	      ["section.title.level5.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/section.title.level5.properties.xml")) t]
	      ["section.title.level6.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/section.title.level6.properties.xml")) t]
	      ["section.title.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/section.title.properties.xml")) t]
	      ["segmentedlist.as.table.xml" (find-file (concat docbook-menu-xsl-dir "/params/segmentedlist.as.table.xml")) t]
	      ["shade.verbatim.style.xml" (find-file (concat docbook-menu-xsl-dir "/params/shade.verbatim.style.xml")) t]
	      ["shade.verbatim.xml" (find-file (concat docbook-menu-xsl-dir "/params/shade.verbatim.xml")) t]
	      ["show.comments.xml" (find-file (concat docbook-menu-xsl-dir "/params/show.comments.xml")) t]
	      ["show.revisionflag.xml" (find-file (concat docbook-menu-xsl-dir "/params/show.revisionflag.xml")) t]
	      ["sidebar.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/sidebar.properties.xml")) t]
	      ["spacing.paras.xml" (find-file (concat docbook-menu-xsl-dir "/params/spacing.paras.xml")) t]
	      ["suppress.footer.navigation.xml" (find-file (concat docbook-menu-xsl-dir "/params/suppress.footer.navigation.xml")) t]
	      ["suppress.header.navigation.xml" (find-file (concat docbook-menu-xsl-dir "/params/suppress.header.navigation.xml")) t]
	      ["suppress.navigation.xml" (find-file (concat docbook-menu-xsl-dir "/params/suppress.navigation.xml")) t]
	      ["symbol.font.family.xml" (find-file (concat docbook-menu-xsl-dir "/params/symbol.font.family.xml")) t]
	      ["table.borders.with.css.xml" (find-file (concat docbook-menu-xsl-dir "/params/table.borders.with.css.xml")) t]
	      ["table.cell.border.color.xml" (find-file (concat docbook-menu-xsl-dir "/params/table.cell.border.color.xml")) t]
	      ["table.cell.border.style.xml" (find-file (concat docbook-menu-xsl-dir "/params/table.cell.border.style.xml")) t]
	      ["table.cell.border.thickness.xml" (find-file (concat docbook-menu-xsl-dir "/params/table.cell.border.thickness.xml")) t]
	      ["table.cell.padding.xml" (find-file (concat docbook-menu-xsl-dir "/params/table.cell.padding.xml")) t]
	      ["table.entry.padding.xml" (find-file (concat docbook-menu-xsl-dir "/params/table.entry.padding.xml")) t]
	      ["table.footnote.number.format.xml" (find-file (concat docbook-menu-xsl-dir "/params/table.footnote.number.format.xml")) t]
	      ["table.footnote.number.symbols.xml" (find-file (concat docbook-menu-xsl-dir "/params/table.footnote.number.symbols.xml")) t]
	      ["table.frame.border.color.xml" (find-file (concat docbook-menu-xsl-dir "/params/table.frame.border.color.xml")) t]
	      ["table.frame.border.style.xml" (find-file (concat docbook-menu-xsl-dir "/params/table.frame.border.style.xml")) t]
	      ["table.frame.border.thickness.xml" (find-file (concat docbook-menu-xsl-dir "/params/table.frame.border.thickness.xml")) t]
	      ["table.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/table.properties.xml")) t]
	      ["tablecolumns.extension.xml" (find-file (concat docbook-menu-xsl-dir "/params/tablecolumns.extension.xml")) t]
	      ["target.database.document.xml" (find-file (concat docbook-menu-xsl-dir "/params/target.database.document.xml")) t]
	      ["targets.filename.xml" (find-file (concat docbook-menu-xsl-dir "/params/targets.filename.xml")) t]
	      ["template.xml" (find-file (concat docbook-menu-xsl-dir "/params/template.xml")) t]
	      ["tex.math.delims.xml" (find-file (concat docbook-menu-xsl-dir "/params/tex.math.delims.xml")) t]
	      ["tex.math.file.xml" (find-file (concat docbook-menu-xsl-dir "/params/tex.math.file.xml")) t]
	      ["tex.math.in.alt.xml" (find-file (concat docbook-menu-xsl-dir "/params/tex.math.in.alt.xml")) t]
	      ["textinsert.extension.xml" (find-file (concat docbook-menu-xsl-dir "/params/textinsert.extension.xml")) t]
	      ["title.font.family.xml" (find-file (concat docbook-menu-xsl-dir "/params/title.font.family.xml")) t]
	      ["title.margin.left.xml" (find-file (concat docbook-menu-xsl-dir "/params/title.margin.left.xml")) t]
	      ["toc.indent.width.xml" (find-file (concat docbook-menu-xsl-dir "/params/toc.indent.width.xml")) t]
	      ["toc.list.type.xml" (find-file (concat docbook-menu-xsl-dir "/params/toc.list.type.xml")) t]
	      ["toc.margin.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/toc.margin.properties.xml")) t]
	      ["toc.max.depth.xml" (find-file (concat docbook-menu-xsl-dir "/params/toc.max.depth.xml")) t]
	      ["toc.section.depth.xml" (find-file (concat docbook-menu-xsl-dir "/params/toc.section.depth.xml")) t]
	      ["ulink.footnote.number.format.xml" (find-file (concat docbook-menu-xsl-dir "/params/ulink.footnote.number.format.xml")) t]
	      ["ulink.footnotes.xml" (find-file (concat docbook-menu-xsl-dir "/params/ulink.footnotes.xml")) t]
	      ["ulink.hyphenate.xml" (find-file (concat docbook-menu-xsl-dir "/params/ulink.hyphenate.xml")) t]
	      ["ulink.show.xml" (find-file (concat docbook-menu-xsl-dir "/params/ulink.show.xml")) t]
	      ["ulink.target.xml" (find-file (concat docbook-menu-xsl-dir "/params/ulink.target.xml")) t]
	      ["use.embed.for.svg.xml" (find-file (concat docbook-menu-xsl-dir "/params/use.embed.for.svg.xml")) t]
	      ["use.extensions.xml" (find-file (concat docbook-menu-xsl-dir "/params/use.extensions.xml")) t]
	      ["use.id.as.filename.xml" (find-file (concat docbook-menu-xsl-dir "/params/use.id.as.filename.xml")) t]
	      ["use.id.function.xml" (find-file (concat docbook-menu-xsl-dir "/params/use.id.function.xml")) t]
	      ["use.local.olink.style.xml" (find-file (concat docbook-menu-xsl-dir "/params/use.local.olink.style.xml")) t]
	      ["use.role.as.xrefstyle.xml" (find-file (concat docbook-menu-xsl-dir "/params/use.role.as.xrefstyle.xml")) t]
	      ["use.role.for.mediaobject.xml" (find-file (concat docbook-menu-xsl-dir "/params/use.role.for.mediaobject.xml")) t]
	      ["use.svg.xml" (find-file (concat docbook-menu-xsl-dir "/params/use.svg.xml")) t]
	      ["variablelist.as.blocks.xml" (find-file (concat docbook-menu-xsl-dir "/params/variablelist.as.blocks.xml")) t]
	      ["variablelist.as.table.xml" (find-file (concat docbook-menu-xsl-dir "/params/variablelist.as.table.xml")) t]
	      ["variablelist.max.termlength.xml" (find-file (concat docbook-menu-xsl-dir "/params/variablelist.max.termlength.xml")) t]
	      ["verbatim.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/verbatim.properties.xml")) t]
	      ["xep.extensions.xml" (find-file (concat docbook-menu-xsl-dir "/params/xep.extensions.xml")) t]
	      ["xep.index.item.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/xep.index.item.properties.xml")) t]
	      ["xref.label-page.separator.xml" (find-file (concat docbook-menu-xsl-dir "/params/xref.label-page.separator.xml")) t]
	      ["xref.label-title.separator.xml" (find-file (concat docbook-menu-xsl-dir "/params/xref.label-title.separator.xml")) t]
	      ["xref.properties.xml" (find-file (concat docbook-menu-xsl-dir "/params/xref.properties.xml")) t]
	      ["xref.title-page.separator.xml" (find-file (concat docbook-menu-xsl-dir "/params/xref.title-page.separator.xml")) t]
	      ["xref.with.number.and.title.xml" (find-file (concat docbook-menu-xsl-dir "/params/xref.with.number.and.title.xml")) t]
	      )
	(list "profiling"
	      ["ChangeLog" (find-file (concat docbook-menu-xsl-dir "/profiling/ChangeLog")) t]
	      ["profile-mode.xsl" (find-file (concat docbook-menu-xsl-dir "/profiling/profile-mode.xsl")) t]
	      ["profile.xsl" (find-file (concat docbook-menu-xsl-dir "/profiling/profile.xsl")) t]
	      ["strip-attributes.xsl" (find-file (concat docbook-menu-xsl-dir "/profiling/strip-attributes.xsl")) t]
	      ["xsl2profile.xsl" (find-file (concat docbook-menu-xsl-dir "/profiling/xsl2profile.xsl")) t]
	      )
	(list "template"
	      ["ChangeLog" (find-file (concat docbook-menu-xsl-dir "/template/ChangeLog")) t]
	      ["README" (find-file (concat docbook-menu-xsl-dir "/template/README")) t]
	      ["biblioentry.xsl" (find-file (concat docbook-menu-xsl-dir "/template/biblioentry.xsl")) t]
	      ["testtemplate.xml" (find-file (concat docbook-menu-xsl-dir "/template/testtemplate.xml")) t]
	      ["titlepage.xsl" (find-file (concat docbook-menu-xsl-dir "/template/titlepage.xsl")) t]
	      )
	(list "tools"
	      (list "olink"
		    ["ChangeLog" (find-file (concat docbook-menu-xsl-dir "/tools/olink/ChangeLog")) t]
		    ["olink-common.xsl" (find-file (concat docbook-menu-xsl-dir "/tools/olink/olink-common.xsl")) t]
		    ["olink.xsl" (find-file (concat docbook-menu-xsl-dir "/tools/olink/olink.xsl")) t]
		    ["olinkchunk.xsl" (find-file (concat docbook-menu-xsl-dir "/tools/olink/olinkchunk.xsl")) t]
		    ["olinksum.dtd" (find-file (concat docbook-menu-xsl-dir "/tools/olink/olinksum.dtd")) t]
		    )
	      (list "profile"
		    ["ChangeLog" (find-file (concat docbook-menu-xsl-dir "/tools/profile/ChangeLog")) t]
		    ["profile.xsl" (find-file (concat docbook-menu-xsl-dir "/tools/profile/profile.xsl")) t]
		    )
	      ["ChangeLog" (find-file (concat docbook-menu-xsl-dir "/tools/ChangeLog")) t]
	      )
	(list "xhtml"
	      ["ChangeLog" (find-file (concat docbook-menu-xsl-dir "/xhtml/ChangeLog")) t]
	      ["admon.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/admon.xsl")) t]
	      ["autoidx.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/autoidx.xsl")) t]
	      ["autotoc.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/autotoc.xsl")) t]
	      ["biblio.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/biblio.xsl")) t]
	      ["block.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/block.xsl")) t]
	      ["callout.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/callout.xsl")) t]
	      ["changebars.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/changebars.xsl")) t]
	      ["chunk-code.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/chunk-code.xsl")) t]
	      ["chunk-common.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/chunk-common.xsl")) t]
	      ["chunk.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/chunk.xsl")) t]
	      ["chunker.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/chunker.xsl")) t]
	      ["chunkfast.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/chunkfast.xsl")) t]
	      ["chunktoc.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/chunktoc.xsl")) t]
	      ["component.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/component.xsl")) t]
	      ["division.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/division.xsl")) t]
	      ["docbook.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/docbook.xsl")) t]
	      ["ebnf.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/ebnf.xsl")) t]
	      ["footnote.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/footnote.xsl")) t]
	      ["formal.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/formal.xsl")) t]
	      ["glossary.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/glossary.xsl")) t]
	      ["graphics.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/graphics.xsl")) t]
	      ["html-rtf.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/html-rtf.xsl")) t]
	      ["html.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/html.xsl")) t]
	      ["html2xhtml.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/html2xhtml.xsl")) t]
	      ["htmltbl.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/htmltbl.xsl")) t]
	      ["index.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/index.xsl")) t]
	      ["info.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/info.xsl")) t]
	      ["inline.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/inline.xsl")) t]
	      ["keywords.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/keywords.xsl")) t]
	      ["lists.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/lists.xsl")) t]
	      ["maketoc.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/maketoc.xsl")) t]
	      ["manifest.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/manifest.xsl")) t]
	      ["math.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/math.xsl")) t]
	      ["oldchunker.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/oldchunker.xsl")) t]
	      ["onechunk.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/onechunk.xsl")) t]
	      ["param.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/param.xsl")) t]
	      ["pi.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/pi.xsl")) t]
	      ["profile-chunk-code.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/profile-chunk-code.xsl")) t]
	      ["profile-chunk.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/profile-chunk.xsl")) t]
	      ["profile-docbook.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/profile-docbook.xsl")) t]
	      ["profile-onechunk.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/profile-onechunk.xsl")) t]
	      ["qandaset.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/qandaset.xsl")) t]
	      ["refentry.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/refentry.xsl")) t]
	      ["sections.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/sections.xsl")) t]
	      ["synop.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/synop.xsl")) t]
	      ["table.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/table.xsl")) t]
	      ["task.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/task.xsl")) t]
	      ["titlepage.templates.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/titlepage.templates.xsl")) t]
	      ["titlepage.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/titlepage.xsl")) t]
	      ["toc.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/toc.xsl")) t]
	      ["verbatim.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/verbatim.xsl")) t]
	      ["xref.xsl" (find-file (concat docbook-menu-xsl-dir "/xhtml/xref.xsl")) t]
	      )
	["VERSION" (find-file (concat docbook-menu-xsl-dir "/VERSION")) t]
	)
  "DocBook XSLT stylesheet distro submenu for 'docbook-menu'."
  )
