<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0"><!--
				This stylesheet was autogenerated from the 'createstylesheet.xsl' 
				XSLT stylesheet. It contains template matches for all of the known 
				element declarations found in the W3C or RelaxNG schema passed through 
				this transform.  The template matches are in alphabetical order.
				
				* Notes and Limitations
					- Default namespaces (via the root @targetNamespace or @ns attributes) are
					  automatically picked up and included in the xsl:stylesheet element
						- you can use the 'default' namespace prefix (defaultns) or specify
						  your own, via the 'prefix.name' parameter
					- Does not recurse through imported/included schema files (yet)
					
				
				* createstylesheet.xsl Author: Jim Earley (jim.earley@flatironssolutions.com)
				* modified by Scott Hudson (scott.hudson@flatironssolutions.com)
				
				* Revision History:
					06.06.2006 [Jim E.] - Initial release
					05.29.2008 [Scott Hudson] - created shakespeare2docbook.
-->
<xsl:template match="/"><xsl:apply-templates/></xsl:template>
   <xsl:template match="ACT"><chapter role="act"><xsl:apply-templates /></chapter></xsl:template>
   <xsl:template match="EPILOGUE"><chapter role="epilogue"><xsl:apply-templates /></chapter></xsl:template>
    <xsl:template match="FM"><info><author><personname><firstname>William</firstname><surname>Shakespeare</surname></personname></author><xsl:apply-templates /></info></xsl:template>
   <xsl:template match="GRPDESCR"><xsl:apply-templates /></xsl:template>
   <xsl:template match="INDUCT"><chapter role="induct"><xsl:apply-templates /></chapter></xsl:template>
   <xsl:template match="LINE"><line><xsl:apply-templates /></line></xsl:template>
   <xsl:template match="P"><para><xsl:apply-templates /></para></xsl:template>
    <xsl:template match="PERSONA"><para><personname role="persona"><xsl:apply-templates /></personname></para></xsl:template>
   <xsl:template match="PERSONAE"><preface><xsl:apply-templates /></preface></xsl:template>
    <xsl:template match="PGROUP"><simplelist columns="2"><member><xsl:apply-templates select="PERSONA"/></member><member><xsl:apply-templates select="GRPDESCR"/></member></simplelist></xsl:template>
    <xsl:template match="PLAY"><book xmlns="http://docbook.org/ns/docbook" version="5.0" role="play"><xsl:apply-templates /></book></xsl:template>
   <xsl:template match="PLAYSUBT"><subtitle><xsl:apply-templates /></subtitle></xsl:template>
   <xsl:template match="PROLOGUE"><preface role="prologue"><xsl:apply-templates /></preface></xsl:template>
    <xsl:template match="SCENE"><section role="scene"><xsl:apply-templates /></section></xsl:template>
   <xsl:template match="SCNDESCR"><para role="scndescr"><xsl:apply-templates /></para></xsl:template>
    <xsl:template match="SPEAKER"><speaker role="speaker"><xsl:apply-templates /></speaker></xsl:template>
    <xsl:template match="SPEECH"><dialogue role="speech"><linegroup><xsl:apply-templates /></linegroup></dialogue></xsl:template>
   <xsl:template match="STAGEDIR"><xsl:choose>
       <xsl:when test="parent::LINE"><phrase role="stagedir"><xsl:apply-templates/></phrase></xsl:when>
       <xsl:otherwise><para role="stagedir"><xsl:apply-templates/></para></xsl:otherwise>
   </xsl:choose></xsl:template>
   <xsl:template match="SUBHEAD"><bridgehead role="subhead"><xsl:apply-templates /></bridgehead></xsl:template>
   <xsl:template match="SUBTITLE"><subtitle><xsl:apply-templates /></subtitle></xsl:template>
   <xsl:template match="TITLE"><title><xsl:apply-templates /></title></xsl:template>
</xsl:stylesheet>