#!/bin/bash

# This feels like a job Make ought to be able to do but I couldn't work it out...

XMLFILES=$@
SRCDIR=/sourceforge/docbook/testdocs/tests
DB4UPG=../../tools/db4-upgrade.xsl

if [ ! -d passed -a -d tests ]; then
    cd tests
fi

if [ ! -d passed ]; then
    echo "Directory 'passed' must exist. Are you sure you're in the right place?"
    exit 1
fi


if [ "$XMLFILES" = "" ]; then
    if [ -d unit-tests ]; then
	for f in unit-tests/*.xml; do
	    XMLFILES="$XMLFILES `basename $f`"
	done
    fi

    for f in $SRCDIR/*.xml; do
	XMLFILES="$XMLFILES `basename $f`"
    done
fi

for f in $XMLFILES; do
    srcfile=$f
    if [ -f $SRCDIR/$f ]; then
	srcfile=$SRCDIR/$f
    elif [ -f unit-tests/$f ]; then
	srcfile=unit-tests/$f
    fi

    REBUILD=1
    if [ "$f" = "$srcfile" ]; then
	REBUILD=0
    fi

    if [ -f $f -a $f -nt $srcfile -a $f -nt $DB4UPG ]; then
	REBUILD=0
    fi

    if [ -f passed/$f -a passed/$f -nt $srcfile -a passed/$f -nt $DB4UPG ]; then
	REBUILD=0
    fi

    if grep -e "xmlns\(:[^=]+\)\?=\(.\)http://docbook.org/ns/docbook\2" $srcfile > /dev/null; then
	REBUILD=0
    fi

    if [ ! -f skip/$f ]; then

	if [ "$REBUILD" != "0" ]; then
	    echo -n "Update $f..."
	    xsltproc --novalid --output $f $DB4UPG $srcfile
	elif [ ! -f $f -a "$f" != "$srcfile" ]; then
	    cp $srcfile $f
	fi

	if [ ! -f passed/$f -o $f -nt passed/$f ]; then
	    echo -n "Validate $f..."
	    if jing ../docbook.rng $f; then
		echo "passed"
		mv $f passed/
	    else
		echo -n "Try DocBook+XInclude validate $f..."
		if jing ../docbookxi.rng $f; then
		    echo "passed"
		    mv $f passed/
		else
		    echo "failed"
		fi
	    fi
	fi

    fi
done

TESTCOUNT=`echo $XMLFILES | wc -w`

echo "$TESTCOUNT tests done"
